exports.homePageLang = {
    portal1:'ব্যৱসায়',
    portal2:'নিবিদা',
    portal3:'বিনিয়োগ',
    selectLang:'ভাষা বাচনি কৰক',
    sell_on_ekBazaar:'Ekbazar-ত বিক্ৰী কৰক', 
    oﬀers:'অফাৰ',
    browse_all_offers:'সকলো অফাৰ চাওক',
    seller_add_product_oﬀers:'বিক্ৰেতা - সামগ্ৰীৰ অফাৰ যোগ কৰক',
    buyer_add_requirement_oﬀers:'গ্ৰাহক - প্ৰয়োজনীয় সামগ্ৰীৰ অফাৰ যোগ কৰক',
    search_placeholder:'সামগ্ৰী / সেৱা বিচাৰি চাওক',
    bannerTitle : 'যিকোনো বস্তুৰে, যিকোনো ব্যক্তিৰ সৈতে, যিকোনো ঠাইত ব্যৱসায় কৰক',
    p : 'বিশ্বজুৰি বিক্ৰী কৰক । ৩০ দিনৰ বাবে বিনামূলীয়া পৰীক্ষা',
    btn : 'Try 30 Days Free!',  
    browseby: 'চোৱা হৈছেঃ',
    browsebyPara:'আপোনাৰ ব্যৱসায়ৰ উপযোগী হোৱাকৈ সঠিক সামগ্ৰী আৰু বিক্ৰেতা বাচনি কৰক। যিকোনো সময়ত যিকোনো ঠাইৰ বিক্ৰেতাৰ সৈতে যোগাযোগ কৰাৰ ক্ষেত্ৰত বিশ্বাসযোগ্য।', 
    rfqTitle : 'দেশজুৰি সকলো বিক্ৰেতাৰ পৰা কোট (সাম্ভাব্য ব্যয়ৰ তালিকা) লাভ কৰক।',
    rfqBody :'আপোনাৰ প্ৰয়োজনসমূহ দাখিল কৰক আৰু বিভিন্ন বিক্ৰেতাৰ পৰা কোট (সাম্ভাব্য ব্যয়ৰ তালিকা) লাভ কৰক।',
    glbMrketTitle:'গোলকীয় বজাৰ',
    glbMrketBody:'আপোনাৰ ব্যৱসায়ৰ বাবে ক্ৰয় কৰা সহজ কৰি তোলে',
    activeSupplierCount:'১.৭৫',
    activeSupplier:'কোটিৰ অধিক সক্ৰিয় বিক্ৰেতা',
    countriesCount:'১৭৫',
    countries:'-ৰো অধিক দেশৰ',
    categoriesCount:'৩০০০',
    categories:'-ৰো অধিক শ্ৰেণী',
    languagesCount:'২০',
    languages:'-ৰো অধিক ভাষা',
    tradeGuideTitle:'ট্ৰেড বজাৰ কেনেকৈ চলে',
    tradeGuideLabel1:'সামগ্ৰী / সেৱাৰ বাবে তালিকা বনাওক বা বিচাৰি চাওক',
    tradeGuideLabel2:'বিক্ৰেতা আৰু গ্ৰাহকৰ সবিশেষ চাওক বা লিখক',
    tradeGuideLabel3:'বিক্ৰেতা আৰু গ্ৰাহকৰ সৈতে পোনপটীয়া সম্পৰ্ক কৰক',
    tradeGuideLabel4:'দাম আলোচনা কৰক আৰু লেনদেন নিশ্চিত কৰক',
    tradeGuideBody1:'Support entrepreneurs by investing in bright ideas',
    tradeGuideBody2:'Evaluate price, seller details and location',
    tradeGuideBody3:'Negotiate and conclude',
    tradeGuideBody4:'Complete transaction with optional EkBazaar services',
    plansTitle:'আপোনাৰ ব্যৱসায় বঢ়াবৰ বাবে ক্ৰয়সাধ্য আঁ‌চনি',
    planBody:'আপোনাৰ বাবে সঠিক যেন লগাটো বাচনি কৰক',
    planTab1:'কৃষক',
    planTab2:'কাৰিকৰ',
    planTab3:'উৎপাদক / ব্যৱসায়ী',
    footerNotifier:'সমগ্ৰ ভাৰতৰ হাজাৰৰো অধিক বিক্ৰেতাৰ সৈতে যোগাযোগ কৰক',
    footerNotifierBtn1:'Try 30 Days Free',
    footerNotifierBtn2:'Subscribe Now',
    testimonialTitle:'সমগ্ৰ ভাৰতৰে বিক্ৰেতা আৰু গ্ৰাহকৰ দ্বাৰা বিশ্বাসযোগ্য',
    testimonialHeader1:'ব্যৱসায়ৰ বৃদ্ধি',
    testimonialHeader2:'অনলাইন উপস্থিতি',
    testimonialHeader3:'সুচল অভিজ্ঞতা',
    testimonialBody1:'আমাৰ সামগ্ৰীবোৰ ট্ৰেডবজাৰত তালিকাভুক্ত কৰাৰ পিছত আমি আমাৰ সামগ্ৰীৰ বিষয়ে বেছিকৈ অনুসন্ধান লাভ কৰিছোঁ। এই প্লেটফৰ্মত আমাৰ ব্যৱসায় অতি সোনকালে বাঢ়িব ধৰিছে।',
    testimonialBody2:'ট্ৰেডবজাৰে এছএমই-বোৰৰ বাবে এক অনলাইন উপস্থিতি থকাটো সহজ কৰি তুলিছে। এতিয়া আমি ভাৰতৰ যিকোনো ঠাইৰ গ্ৰাহকৰ সৈতে সহজে যোগাযোগ কৰিব পৰা হৈছোঁ।',
    testimonialBody3:'মোৰ খাদ্য প্ৰক্ৰমণ ব্যৱসায়ৰ বাবে কেঁ‌চা সামগ্ৰী কিনাটো এতিয়া একেবাৰে সহজ হৈ পৰিছে। মাত্ৰ এখন ফৰ্ম দাখিল কৰিয়েই মই বিভিন্ন বিক্ৰেতাৰ পৰা কোট (সাম্ভাব্য খৰচৰ তালিকা) লাভ কৰিব পাৰিছোঁ।',
    testimonialAuthor1:'অমন মিট্টাল',
    testimonialAuthor2:'Sumanth Verma',
    testimonialAuthor3:'Radha Naik',
    testimonialCmp1:'কে এ জাৰমেন্টছ',
    testimonailCmp2:'সুমন্থ বৰ্মা',
    testimonialCmp3:'এমটেক প্ৰাইঃ লিঃ',
    recomendedPrjTitle:'Recommended For You',
    chat_with_seller:'বিক্ৰেতাৰ সৈতে কথা পাতক'
}