exports.homePageLang = {
    portal1:'ব্যবসা',
    portal2:'টেন্ডার',
    portal3:'বিনিয়োগ',
    selectLang:'ভাষা নির্বাচন করুন',
    sell_on_ekBazaar:'একবাজারে বিক্রি করুন', 
    oﬀers:'অফার',
    browse_all_offers:'সমস্ত অফারগুলি ব্রাউজ করুন',
    seller_add_product_oﬀers:'বিক্রেতা - পণ্যের অফার যোগ করুন',
    buyer_add_requirement_oﬀers:'ক্রেতা - প্রয়োজনের অফার যোগ করুন',
    search_placeholder:'পণ্য / পরিষেবার খোঁজ করুন',
    bannerTitle : 'যে কোনো কিছুর, যে কারুর সাথে, যে কোন জায়গায় ব্যবসা করুন',
    p : 'বিশ্বব্যাপী বিক্রয় করুন, বিনামূল্যে 30 দিনের ট্র্যায়াল',
    btn : 'Try 30 Days Free!',  
    browseby: 'এই অনুসারে ব্রাউজ করুন',
    browsebyPara:'আপনার ব্যবসার প্রয়োজন অনুসারে সঠিক পণ্য এবং সরবরাহকারীদের খুঁজে পান। যে কোনও সময়, যে কোনও স্থানে যোগাযোগ করার সুবিধা।', 
    rfqTitle : 'দেশব্যাপী সরবরাহকারীদের থেকে কোটেশন পান',
    rfqBody :'আপনার প্রয়োজন জানান, এবং একাধিক সরবরাহকারীদের কাছ থেকে কোটেশন পান',
    glbMrketTitle:'বিশ্বব্যাপী বাজার',
    glbMrketBody:'আপনার ব্যবসার জন্য সহজে ক্রয় করা',
    activeSupplierCount:'1.75 কোটি+',
    activeSupplier:'সক্রিয় সরবরাহকারী',
    countriesCount:'175+',
    countries:'দেশ',
    categoriesCount:'3000+',
    categories:'শ্রেণি',
    languagesCount:'20+',
    languages:'ভাষা',
    tradeGuideTitle:'ট্রেড বাজার কীভাবে কাজ করে',
    tradeGuideLabel1:'পণ্য/পরিষেবার তালিকা করুন অথবা খোঁজ করুন',
    tradeGuideLabel2:'ক্রেতা ও বিক্রেতার বিশদ পোস্ট করুন অথবা দেখুন',
    tradeGuideLabel3:'ক্রেতা ও বিক্রেতারা সরাসরি যোগাযোগ করুন',
    tradeGuideLabel4:'মূল্য নিয়ে আলোচনা করুন এবং চুক্তিটি সম্পন্ন করুন',
    tradeGuideBody1:'Support entrepreneurs by investing in bright ideas',
    tradeGuideBody2:'Evaluate price, seller details and location',
    tradeGuideBody3:'Negotiate and conclude',
    tradeGuideBody4:'Complete transaction with optional EkBazaar services',
    plansTitle:'আপনার ব্যবসায়ের বৃদ্ধি করার জন্য সামর্থ্যের মধ্যে পরিকল্পনা।',
    planBody:'আপনার জন্য যেটি উপযুক্ত সেটি নির্বাচন করুন',
    planTab1:'কৃষক',
    planTab2:'কারূশিল্পী',
    planTab3:'নির্মাতা/ব্যবসায়ী',
    footerNotifier:'সারা ভারত জুড়ে হাজার হাজার ক্রেতার কাছে পৌঁছে যান',
    footerNotifierBtn1:'Try 30 Days Free',
    footerNotifierBtn2:'Subscribe Now',
    testimonialTitle:'ভারত জুড়ে বিশ্বস্ত ক্রেতা এবং বিক্রেতা',
    testimonialHeader1:'ব্যবসার বৃদ্ধি',
    testimonialHeader2:'অনলাইন উপস্থিতি',
    testimonialHeader3:'মসৃণ অভিজ্ঞতা',
    testimonialBody1:'ট্রেডবাজারে আমাদের পণ্যগুলি তালিকাভুক্ত করার পরে, আমরা আরও বেশি ব্যবসায়ীক অনুসন্ধান পাচ্ছি। এই প্ল্যাটফর্মে আমাদের ব্যবসা দ্রুত বাড়ছে',
    testimonialBody2:'ট্রেডবাজার এসএমই-দের অনলাইন উপস্থিতি সহজ করেছে। এখন আমরা ভারতের যে কোনও স্থানের ক্রেতাদের সাথে যোগাযোগ করতে পারি।',
    testimonialBody3:'আমার খাদ্য প্রক্রিয়াকরণের ব্যবসার জন্য কাঁচামাল কেনা এখন চাপ-মুক্ত। শুধুমাত্র একটি ফর্মেই আমি সরবরাহকারীদের থেকে একাধিক কোটেশন পেতে পারি।',
    testimonialAuthor1:'আমন মিত্তাল',
    testimonialAuthor2:'সুমন্থ ভার্মা',
    testimonialAuthor3:'রাধা নায়েক',
    testimonialCmp1:'কেএ গার্মেন্টস',
    testimonailCmp2:'অ্যামটেক প্রাঃ লিঃ',
    testimonialCmp3:'ডেলিশাস ফুডস প্রাঃ লিঃ',
    recomendedPrjTitle:'Recommended For You',
    chat_with_seller:'বিক্রেতার সাথে চ্যাট করুন'
}