exports.homePageLang = {
    portal1:'Trade',
    portal2:'Tender',
    portal3:'Investment',
    selectLang:'Select Language',
    sell_on_ekBazaar:'Sell on EkBazaar', 
    oﬀers:'Oﬀers',
    browse_all_offers:'Browse All Offers',
    seller_add_product_oﬀers:'Seller - Add Product Oﬀers',
    buyer_add_requirement_oﬀers:'Buyer - Add Requirement Oﬀers',
    search_placeholder:'Search Products/Services',
    bannerTitle : 'Trade anything, with anyone, anywhere',
    p : 'Sell Worldwide. 30 day free trial.',
    btn : 'Try 30 Days Free!',  
    browseby: 'Browse by',
    browsebyPara:'Find the right products and suppliers to suit your business needs. Convenience of connecting with sellers anytime, anywhere.', 
    rfqTitle : 'Get quotes from nationwide suppliers',
    rfqBody :'Enter your requirement and get quotes from multiple suppliers',
    glbMrketTitle:'Global Marketplace',
    glbMrketBody:'Buying for your business made easy',
    activeSupplierCount:'1.75 Cr+',
    activeSupplier:'Active Suppliers',
    countriesCount:'175+',
    countries:'Countries',
    categoriesCount:'3000+',
    categories:'Categories',
    languagesCount:'20+',
    languages:'Languages',
    tradeGuideTitle:'How Trade Bazaar Works',
    tradeGuideLabel1:'List or search for products/services',
    tradeGuideLabel2:'Post or view seller and buyer details',
    tradeGuideLabel3:'Sellers and buyers connect directly',
    tradeGuideLabel4:'Discuss prices and seal the deal',
    tradeGuideBody1:'Support entrepreneurs by investing in bright ideas',
    tradeGuideBody2:'Evaluate price, seller details and location',
    tradeGuideBody3:'Negotiate and conclude',
    tradeGuideBody4:'Complete transaction with optional EkBazaar services',
    plansTitle:'Aﬀordable plans to grow your business.',
    planBody:'Choose the one that’s right for you ',
    planTab1:'Farmer',
    planTab2:'Craftsman',
    planTab3:'Manufacturers/Traders',
    footerNotifier:'Reach thousands of buyers across India',
    footerNotifierBtn1:'Try 30 Days Free',
    footerNotifierBtn2:'Subscribe Now',
    testimonialTitle:'Trusted by Buyers and Sellers Across India',
    testimonialHeader1:'Business Growth',
    testimonialHeader2:'Online Presence',
    testimonialHeader3:'Smooth Experience',
    testimonialBody1:'After listing our products on TradeBazaar, we have been getting many more trade inquiries. Our business is growing fast with this platform.',
    testimonialBody2:'TradeBazaar has made it simple for SMEs to have an online presence. Now we are able to easily contact buyers anywhere in India.',
    testimonialBody3:'Procuring raw material for my food processing business has become stress-free. With a single form, I can get multiple quotes from suppliers.',
    testimonialAuthor1:'Aman Mittal',
    testimonialAuthor2:'Sumanth Verma',
    testimonialAuthor3:'Radha Naik',
    testimonialCmp1:'KA Garments',
    testimonailCmp2:'AmTech Pvt Ltd',
    testimonialCmp3:'Delicious Foods Pvt Ltd',
    recomendedPrjTitle:'Recommended For You',
    chat_with_seller:'Chat With Seller'
}