exports.homePageLang = {
    portal1:'വ്യാപാരം',
    portal2:'ടെണ്ടർ',
    portal3:'നിക്ഷേപം',
    selectLang:'ഭാഷ തിരഞ്ഞെടുക്കുക',
    sell_on_ekBazaar:'EkBazaar-ൽ വിൽക്കുക', 
    oﬀers:'ഓഫറുകൾ',
    browse_all_offers:'എല്ലാ ഓഫറുകളും ബ്രൗസ് ചെയ്യുക',
    seller_add_product_oﬀers:'വ്യാപാരി - ഉൽപ്പന്ന ഓഫറുകൾ ചേർക്കുക',
    buyer_add_requirement_oﬀers:'ഉപഭോക്താവ് - ആവശ്യകതകളുമായി ബന്ധപ്പെട്ട ഓഫറുകൾ ചേർക്കുക',
    search_placeholder:'ഉൽപ്പന്നങ്ങൾ/സേവനങ്ങൾ തിരയുക',
    bannerTitle : 'ആരുമായും എവിടെനിന്നും എന്തും വിൽപ്പന നടത്തൂ',
    p : 'ലോകമെമ്പാടും വിൽക്കുക. 30 ദിവസത്തെ സൗജന്യ ട്രയൽ',
    btn : 'Try 30 Days Free!',  
    browseby: 'ഇനിപ്പറയുന്നത് പ്രകാരം ബ്രൗസ് ചെയ്യുക',
    browsebyPara:'നിങ്ങളുടെ ബിസിനസ് ആവശ്യങ്ങൾക്ക് അനുയോജ്യമായ ഉൽപ്പന്നങ്ങളും സപ്ലയർമാരെയും കണ്ടെത്തുക. എപ്പോൾ വേണമെങ്കിലും എവിടെനിന്ന് വേണമെങ്കിലും വിൽപ്പനക്കാരുമായി ബന്ധപ്പെടാനുള്ള സൗകര്യവും.', 
    rfqTitle : 'രാജ്യമെമ്പാടുമുള്ള സപ്ലയർമാരിൽ നിന്ന് ക്വോട്ടുകൾ നേടൂ',
    rfqBody :'നിങ്ങളുടെ ആവശ്യകത നൽകിയതിന് ശേഷം ഒന്നിലധികം സപ്ലയർമാരിൽ നിന്ന് ക്വോട്ടുകൾ നേടുക',
    glbMrketTitle:'ഗ്ലോബൽ മാർക്കറ്റ്‌പ്ലേസ്',
    glbMrketBody:'നിങ്ങളുടെ ബിസിനസ്സിനായി വാങ്ങുന്നത് എളുപ്പമാക്കിയിരിക്കുന്നു',
    activeSupplierCount:'1.75 Cr+',
    activeSupplier:'സജീവ സപ്ലയർമാർ',
    countriesCount:'175+',
    countries:'രാജ്യങ്ങൾ',
    categoriesCount:'3000+',
    categories:'വിഭാഗങ്ങൾ',
    languagesCount:'20+',
    languages:'ഭാഷകൾ',
    tradeGuideTitle:'Trade Bazaar എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    tradeGuideLabel1:'ഉൽപ്പന്നങ്ങൾ/സേവനങ്ങൾ ലിസ്റ്റ് ചെയ്യുക അല്ലെങ്കിൽ തിരയുക',
    tradeGuideLabel2:'വിൽക്കുന്നയാളുടെയും വാങ്ങുന്നയാളുടെയും വിശദാംശങ്ങൾ പോസ്റ്റ് ചെയ്യുക അല്ലെങ്കിൽ കാണുക',
    tradeGuideLabel3:'വിൽപ്പനക്കാരും ഉപഭോക്താക്കളും നേരിട്ട് ബന്ധപ്പെടുന്നു',
    tradeGuideLabel4:'വിലകൾ ചർച്ച ചെയ്ത് ഇടപാട് സ്ഥിരീകരിക്കുന്നു',
    tradeGuideBody1:'Support entrepreneurs by investing in bright ideas',
    tradeGuideBody2:'Evaluate price, seller details and location',
    tradeGuideBody3:'Negotiate and conclude',
    tradeGuideBody4:'Complete transaction with optional EkBazaar services',
    plansTitle:'നിങ്ങളുടെ ബിസിനസ്സ് വളർത്തിയെടുക്കാനുള്ള ചെലവ് കുറഞ്ഞ പ്ലാനുകൾ.',
    planBody:'നിങ്ങൾക്ക് അനുയോജ്യമായ ഒന്ന് തിരഞ്ഞെടുക്കുക',
    planTab1:'കൃഷി ചെയ്യുന്നയാൾ',
    planTab2:'കരകൗശല തൊഴിലാളി',
    planTab3:'നിർമ്മാതാക്കൾ/വ്യാപാരികൾ',
    footerNotifier:'ഇന്ത്യയിലുടനീളമുള്ള ആയിരക്കണക്കിന് ഉപഭോക്താക്കളിലേക്ക് എത്തിച്ചേരൂ',
    footerNotifierBtn1:'Try 30 Days Free',
    footerNotifierBtn2:'Subscribe Now',
    testimonialTitle:'ഇന്ത്യയിലുടനീളമുള്ള ഉപഭോക്താക്കളും വിൽപ്പനക്കാരും വിശ്വാസമർപ്പിക്കുന്നത്',
    testimonialHeader1:'ബിസിനസ്സിൻ്റെ വളർച്ച',
    testimonialHeader2:'ഓൺലൈൻ സാന്നിധ്യം',
    testimonialHeader3:'സുഗമമായ അനുഭവം',
    testimonialBody1:'TradeBazaar-ൽ ഞങ്ങളുടെ ഉൽപ്പന്നങ്ങൾ ലിസ്റ്റ് ചെയ്തതിനുശേഷം, ഞങ്ങൾക്ക് വിൽപ്പനയുമായി ബന്ധപ്പെട്ട് കൂടുതൽ അന്വേഷണങ്ങൾ ലഭിക്കുന്നുണ്ട്. ഈ പ്ലാറ്റ്‌ഫോമിലൂടെ ഞങ്ങളുടെ ബിസിനസ്സ് അതിവേഗം വളരുന്നു',
    testimonialBody2:'എസ്‌എം‌ഇകളുടെ ഓൺലൈൻ സാന്നിധ്യം TradeBazaar ലളിതമാക്കിയിരിക്കുന്നു. ഇപ്പോൾ നമുക്ക് ഇന്ത്യയിൽ എവിടെ നിന്നും  ഉപഭോക്താക്കളുമായി എളുപ്പത്തിൽ ബന്ധപ്പെടാൻ കഴിയും.',
    testimonialBody3:'എൻ്റെ ഫുഡ് പ്രൊസസിംഗ് ബിസിനസ്സിനായി അസംസ്കൃത വസ്തുക്കൾ വാങ്ങുന്നത് സമ്മർദ്ദമില്ലാത്ത കാര്യമായി മാറിയിരിക്കുന്നു. ഒരൊറ്റ ഫോം ഉപയോഗിച്ച് സപ്ലയർമാരിൽ നിന്ന് ഒന്നിലധികം ക്വോട്ടുകൾ നേടാൻ കഴിയും.',
    testimonialAuthor1:'അമൻ മിത്തൽ',
    testimonialAuthor2:'സുമന്ത് വർമ്മ',
    testimonialAuthor3:'രാധാ നായിക്',
    testimonialCmp1:'കെഎ ഗാർമെന്‍റ്സ്',
    testimonailCmp2:'ആംടെക് പ്രൈവറ്റ് ലിമിറ്റഡ്',
    testimonialCmp3:'ഡെലീഷ്യസ് ഫുഡ്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്',
    recomendedPrjTitle:'Recommended For You',
    chat_with_seller:'വ്യാപാരിയുമായി സംസാരിക്കുക'
}