exports.homePageLang = {
    portal1:'ट्रेड',
    portal2:'टेंडर',
    portal3:'गुंतवणूक',
    selectLang:'भाषा निवडा',
    sell_on_ekBazaar:'EkBazaarवर विका', 
    oﬀers:'ऑफर्स',
    browse_all_offers:'सर्व ऑफर्स जाणून घ्या',
    seller_add_product_oﬀers:'सेलर - प्रोडक्ट ऑफर्स अॅड करा',
    buyer_add_requirement_oﬀers:'खरेदीदार - आवश्यकता ऑफर्स अॅड करा',
    search_placeholder:'प्रोडक्ट्स/सेवा शोधा',
    bannerTitle : 'कसलाही व्यापार करा, कुणाशीही, कुठेही',
    p : 'जगभरात विक्री करा. ३० दिवसांची फ्री ट्रायल',
    btn : 'Try 30 Days Free!',  
    browseby: 'या प्रकारे ब्राउझ करा',
    browsebyPara:'तुमच्या व्यवसायाच्या आवश्यकतांनुसार योग्य प्रोडक्ट्स आणि सप्लायर्स शोधा. सेलर्सशी कधीही, कुठेही जोडले जाण्याची सुविधा.', 
    rfqTitle : 'देशभरातील पुरवठादारांकडून क्वोटेशन मिळवा',
    rfqBody :'तुमची आवश्यकता एंटर करा आणि वेगवेगळ्या सप्लायर्सकडून क्वोटेशन मिळवा',
    glbMrketTitle:'जागतिक बाजारपेठ',
    glbMrketBody:'तुमच्या बिझनेससाठी खरेदी करणे झाले सोपे',
    activeSupplierCount:'१.७५+ कोटी',
    activeSupplier:'सक्रीय पुरवठादार',
    countriesCount:'१७५+',
    countries:'देश',
    categoriesCount:'३०००+',
    categories:'विभाग',
    languagesCount:'२०+',
    languages:'भाषा',
    tradeGuideTitle:'TradeBazaar कसे काम करते',
    tradeGuideLabel1:'प्रोडक्ट्स/सेवा यांचे लिस्टिंग करा किंवा शोधा',
    tradeGuideLabel2:'सेलर आणि खरेदीदाराचा तपशील पोस्ट करा किंवा पाहा',
    tradeGuideLabel3:'सेलर्स आणि खरेदीदार थेट जोडले जातात',
    tradeGuideLabel4:'किमतीविषयी चर्चा करा आणि व्यवहार पक्का करा',
    tradeGuideBody1:'Support entrepreneurs by investing in bright ideas',
    tradeGuideBody2:'Evaluate price, seller details and location',
    tradeGuideBody3:'Negotiate and conclude',
    tradeGuideBody4:'Complete transaction with optional EkBazaar services',
    plansTitle:'तुमचा बिझनेस वाढविण्यासाठी किफायतशीर प्लॅन्स',
    planBody:'तुमच्यासाठी सुयोग्य असलेला प्लॅन निवडा',
    planTab1:'शेतकरी',
    planTab2:'कारागीर',
    planTab3:'उत्पादक / ट्रेडर',
    footerNotifier:'भारतभरातील हजारो खरेदीदारांपर्यंत पोहोचा',
    footerNotifierBtn1:'Try 30 Days Free',
    footerNotifierBtn2:'Subscribe Now',
    testimonialTitle:'भारतभरातील खरेदीदार आणि विक्रेत्यांचा विश्वास असलेले',
    testimonialHeader1:'बिझनेसची वाढ',
    testimonialHeader2:'ऑनलाइन अस्तित्व',
    testimonialHeader3:'सुलभ अनुभव',
    testimonialBody1:'TradeBazaarवर आमच्या प्रोडक्ट्सचे लिस्टिंग केल्यानंतर आमच्याकडे अधिक प्रमाणात व्यापारासंबंधी विचारणा केली जात आहे. या प्लॅटफॉर्ममुळे आमचा बिझनेस वेगाने वाढत आहे',
    testimonialBody2:'TradeBazaar लघु व मध्यम उद्योगांना ऑनलाइन अस्तित्व तयार करणे सोपे झाले आहे. आता आम्ही भारतातील कोणत्याही भागातील खरेदीदारांशी सहज संपर्क साधू शकतो.',
    testimonialBody3:'माझ्या अन्नप्रक्रिया उद्योगासाठी कच्चा माल प्राप्त करणे आता सुलभ झाले आहे. एक फॉर्म भरून मला विविध सप्लायर्सकडून क्वोटेशन मिळू शकते.',
    testimonialAuthor1:'अमन मित्तल',
    testimonialAuthor2:'सुमंत वर्मा',
    testimonialAuthor3:'राधा नाइक',
    testimonialCmp1:'केए गारमेंट्स',
    testimonailCmp2:'अॅमटेक प्रा. लि.',
    testimonialCmp3:'डिलिशिअस फुड्स प्रा. लि.',
    recomendedPrjTitle:'Recommended For You',
    chat_with_seller:'सेलरशी चॅट करा'
}