exports.homePageLang = {
    portal1:'வர்த்தகம்',
    portal2:'ஒப்பந்தப்புள்ளி',
    portal3:'முதலீடு',
    selectLang:'மொழியைத் தேர்ந்தெடுக்கவும்',
    sell_on_ekBazaar:'ஏக்பஜாரில் விற்கவும்', 
    oﬀers:'சலுகைகள்',
    browse_all_offers:'அனைத்து சலுகைகளையும் உலாவுக',
    seller_add_product_oﬀers:'விற்பனையாளர் - தயாரிப்பு சலுகைகளைச் சேர்க்கவும்',
    buyer_add_requirement_oﬀers:'வாங்குபவர் - தேவைகள் சலுகைகளைச் சேர்க்கவும்',
    search_placeholder:'தயாரிப்புகள்/சேவைகளைத் தேடுக',
    bannerTitle : 'எதையும், யாருடனும், எங்கும் வர்த்தகம் செய்யவும்',
    p : 'உலகளாவிய வகையில் விற்கவும். 30 நாள் இலவச சோதனை.',
    btn : 'Try 30 Days Free!',  
    browseby: 'இவ்வாறாக உலாவுக',
    browsebyPara:'உங்கள் வணிகத் தேவைகளுக்கு ஏற்ப சரியான தயாரிப்புகள் மற்றும் வினியோகஸ்தர்களைக் கண்டறியவும். எந்த நேரத்திலும், எந்த இடத்திலும் விற்பனையாளர்களுடன் இணைக்கும் வசதி.', 
    rfqTitle : 'நாடு தழுவிய வினியோகஸ்தர்களிடமிருந்து விலை கூறல்களைப் பெறவும்',
    rfqBody :'உங்கள் தேவையை உள்ளிட்டு பல வினியோகஸ்தர்களிடமிருந்து விலைகூறல்களைப் பெறவும்',
    glbMrketTitle:'உலகளாவிய சந்தை',
    glbMrketBody:'உங்கள் வணிகத்திற்காக வாங்குவது எளிதாக்கப்பட்டது',
    activeSupplierCount:'1.75 கோடி+',
    activeSupplier:'செயலில் உள்ள வினியோகஸ்தர்கள்',
    countriesCount:'175+',
    countries:'நாடுகள்',
    categoriesCount:'3000+',
    categories:'வகைகள்',
    languagesCount:'20+',
    languages:'மொழிகள்',
    tradeGuideTitle:'டிரேட்பஜார் எவ்வாறு வேலை செய்கிறது',
    tradeGuideLabel1:'தயாரிப்புகள்/சேவைகளை பட்டியலிடவும் அல்லது தேடவும்',
    tradeGuideLabel2:'விற்பனையாளர் மற்றும் வாங்குபவர் விவரங்களை இடுகையிடவும் அல்லது பார்வையிடவும்',
    tradeGuideLabel3:'விற்பனையாளர்கள் மற்றும் வாங்குபவர்கள் நேரடியாக இணைகிறார்கள்',
    tradeGuideLabel4:'விலைகளை விவாதித்து ஒப்பந்தத்தை முடிக்கிறார்கள்',
    tradeGuideBody1:'Support entrepreneurs by investing in bright ideas',
    tradeGuideBody2:'Evaluate price, seller details and location',
    tradeGuideBody3:'Negotiate and conclude',
    tradeGuideBody4:'Complete transaction with optional EkBazaar services',
    plansTitle:'உங்கள் வணிகத்தை மேம்படுத்த மலிவான திட்டங்கள்.',
    planBody:'உங்களுக்கு ஏற்ற ஒன்றை தேர்வு செய்யவும்',
    planTab1:'விவசாயி',
    planTab2:'கைவினைஞர்',
    planTab3:'உற்பத்தியாளர்கள்/வர்த்தகர்கள்',
    footerNotifier:'இந்தியா முழுவதும் ஆயிரக்கணக்கான வாங்குபவர்களை அணுகவும்',
    footerNotifierBtn1:'Try 30 Days Free',
    footerNotifierBtn2:'Subscribe Now',
    testimonialTitle:'இந்தியா முழுவதும் வாங்குபவர்கள் மற்றும் விற்பனையாளர்களால் நம்பப்படுகிறது',
    testimonialHeader1:'வணிக வளர்ச்சி',
    testimonialHeader2:'ஆன்லைன் இருப்பு',
    testimonialHeader3:'மென்மையான அனுபவம்',
    testimonialBody1:'டிரேட்பஜாரில் எங்கள் தயாரிப்புகளை பட்டியலிட்ட பிறகு, நாங்கள் இன்னும் பல வர்த்தக விசாரணைகளை பெற்று வருகிறோம். இந்த தளத்துடன் எங்கள் வணிகம் வேகமாக வளர்ந்து வருகிறது',
    testimonialBody2:'டிரேட்பஜார் எஸ்.எம்.ஈ. களுக்கு ஆன்லைன் இருப்பை எளிதாக்கியுள்ளது.இப்போது எங்களால் இந்தியாவில் எங்கு வேண்டுமானாலும் வாங்குபவர்களை எளிதில் தொடர்பு கொள்ள முடிகிறது.',
    testimonialBody3:'எனது உணவு பதப்படுத்தும் வணிகத்திற்கான மூலப்பொருளை கொள்முதல் செய்வது மன அழுத்தமில்லாமல் போய்விட்டது. ஒரு படிவத்துடன், என்னால் வினியோகஸ்தர்களிடமிருந்து பல விலைகூறல்களைப் பெற முடிகிறது.',
    testimonialAuthor1:'அமன் மிட்டல்',
    testimonialAuthor2:'சுமந்த் வர்மா',
    testimonialAuthor3:'ராதா நாயக்',
    testimonialCmp1:'கேஏ ஆடைகள்',
    testimonailCmp2:'ஆம்டெக் பிரைவேட் லிமிடெட்',
    testimonialCmp3:'டெலிஷியஸ் ஃபுட்ஸ் பிரைவேட் லிமிடெட்',
    recomendedPrjTitle:'Recommended For You',
    chat_with_seller:'விற்பனையாளருடன் உரையாடவும்'
}