exports.homePageLang = {
    portal1:'ట్రేడ్',
    portal2:'టెండర్',
    portal3:'పెట్టుబడి',
    selectLang:'భాషను ఎంచుకోండి',
    sell_on_ekBazaar:'ఏక్‌బజార్‌పై అమ్మండి', 
    oﬀers:'ఆఫర్లు',
    browse_all_offers:'అన్ని ఆఫర్లను బ్రౌజ్ చేయండి',
    seller_add_product_oﬀers:'అమ్మకందారు-ఉత్పత్తుల ఆఫర్లను చేర్చండి',
    buyer_add_requirement_oﬀers:'కొనుగోలుదారు-అవసర ఆఫర్లను చేర్చండి',
    search_placeholder:'ఉత్పత్తులు/సేవలను శోధించండి',
    bannerTitle : 'ఎవరితోనైనా, ఎక్కడినుండైనా, వ్యాపారం చేయండి',
    p : 'ప్రపంచవ్యాప్తంగా అమ్మండి. 30-రోజుల ఉచిత ట్రయల్.',
    btn : 'Try 30 Days Free!',  
    browseby: 'బ్రౌజ్ చేయండి',
    browsebyPara:'మీ వ్యాపార అవసరాలకు సరిపోయే సరైన ఉత్పత్తులు మరియు సరఫరాదారులను కనుగొనండి. ఏ సమయంలోనైనా, ఎక్కడినుండైనా అమ్మకందారులతో కనెక్ట్ అయ్యే సౌకర్యం.', 
    rfqTitle : 'దేశవ్యాప్తంగా ఉన్న సరఫరాదారుల నుండి కోట్స్ పొందండి',
    rfqBody :'మీ అవసరాన్ని ఎంటర్ చేయండి మరియు బహుళ సరఫరాదారుల నుండి కోట్స్ పొందండి',
    glbMrketTitle:'ప్రపంచవ్యాప్త మార్కెట్‌ప్లేస్',
    glbMrketBody:'మీవ్యాపారానికి కొనుగోలు చేయడం సులభం చేయబడింది',
    activeSupplierCount:'1.75 కోట్లు+',
    activeSupplier:'పనిచేస్తున్న సరఫరాదారులు',
    countriesCount:'175+',
    countries:'దేశాలు',
    categoriesCount:'3000+',
    categories:'కేటగిరీలు',
    languagesCount:'20+',
    languages:'భాషలు',
    tradeGuideTitle:'ట్రేడ్‌బజార్ ఎలా పనిచేస్తుంది',
    tradeGuideLabel1:'ఉత్పత్తులు/సేవలను లిస్ట్ చేయండి లేదా శోధించండి',
    tradeGuideLabel2:'అమ్మకందారు మరియు కొనుగోలుదారు వివరాలు పోస్ట్ చేయండి లేదా వీక్షించండి',
    tradeGuideLabel3:'అమ్మకందారులు మరియు కొనుగోలుదారులతో నేరుగా కనెక్ట్ అవండి',
    tradeGuideLabel4:'ధరలను చర్చింది డీల్ పూర్తిచేసుకోండి',
    tradeGuideBody1:'Support entrepreneurs by investing in bright ideas',
    tradeGuideBody2:'Evaluate price, seller details and location',
    tradeGuideBody3:'Negotiate and conclude',
    tradeGuideBody4:'Complete transaction with optional EkBazaar services',
    plansTitle:'మీ వ్యాపారాన్ని పెంపొందించుకొనేందుకు అనువుగా ఉండే ప్రణాళికలు ఉండే ప్రణాళికలు.',
    planBody:'మీకు సరిపోయే ఒకదానిని ఎంచుకోండి',
    planTab1:'రైతు',
    planTab2:'హస్తకళాకారుడు',
    planTab3:'తయారీదారులు/వర్తకులు',
    footerNotifier:'భారతదేశమంతటా విస్తరించివున్న వేలకొద్దీ కొనుగోలుదారులను చేరుకోండి',
    footerNotifierBtn1:'Try 30 Days Free',
    footerNotifierBtn2:'Subscribe Now',
    testimonialTitle:'భారతదేశమంతటా ఉన్న కొనుగోలుదారులు మరియు అమ్మకందారులచే విశ్వసించబడినది',
    testimonialHeader1:'వ్యాపార అభివృద్ధి',
    testimonialHeader2:'ఆన్‌లైన్‌లో లభ్యత',
    testimonialHeader3:'సరళమైన అనుభవం',
    testimonialBody1:'మా వస్తువులను ట్రేడ్‌బజార్‌పై లిస్ట్ చేసిన తరువాత, మేము ఎన్నో వ్యాపార సంబంధ విచారణలను స్వీకరిస్తున్నాము. ఈ ప్లాట్‍‌ఫారంపై మా  వ్యాపారం వేగవంతంగా పెరుగుతోంది',
    testimonialBody2:'ఎస్‌ఎమ్‌ఇలు ఆన్‌లైన్లో లభ్యతను కలిగివుండటాన్ని ట్రేడ్‌బజార్ సులభతరం చేసింది. ఇప్పుడు మేము భారతదేశంలో ఎక్కడౌన్న కొనుగోలుదారులనైనా సులభంగా చేరుకోవచ్చు.',
    testimonialBody3:'నా ఆహార ప్రాసెసింగ్ వ్యాపారానికి ముడిసరుకును పొందడం ఇప్పుడు చాలా తేలికయింది. కేవలం ఒకేఒక్క ఫారంతో నేను బహుళ సరఫరాదారులనుండి కోట్‌లు పొందగలుగుతున్నాను.',
    testimonialAuthor1:'అమన్ మిట్టల్',
    testimonialAuthor2:'సుమంత్ వర్మ',
    testimonialAuthor3:'రాధా నాయక్',
    testimonialCmp1:'కెఎ గార్మెంట్స్',
    testimonailCmp2:'ఆమ్‌టెక్ ప్రై. లి.',
    testimonialCmp3:'డెలిషియస్ ఫుడ్స్ ప్రై. లి.',
    recomendedPrjTitle:'Recommended For You',
    chat_with_seller:'అమ్మకందారుతో చాట్ చేయండి'
}