export const actionTypes = {
  sso: {
    SSO_REDIRECT: "SSO_REDIRECT",
    SSO_REDIRECT_PENDING: "SSO_REDIRECT_PENDING",
    SSO_REDIRECT_SUCCESS: "SSO_REDIRECT_SUCCESS",
    SSO_REDIRECT_ERROR: "SSO_REDIRECT_ERROR",
  },
  app: {
    SET_COOKIE: 'SET_COOKIE',
    CLEAR_COOKIE: 'CLEAR_COOKIE',

    GET_TOKEN: 'GET_TOKEN',
    SET_TOKEN: 'SET_TOKEN',
    CLEAR_TOKEN: 'CLEAR_TOKEN',

    MODAL_SHOW: 'MODAL_SHOW',
    MODAL_HIDE: 'MODAL_HIDE',

    AUTO_MODAL_SHOW: 'AUTO_MODAL_SHOW',
    AUTO_MODAL_HIDE: 'AUTO_MODAL_HIDE',

    SET_ALERT: 'SET_ALERT',
    CLEAR_ALERT: 'CLEAR_ALERT',

    REDIRECT_WITH_FILTER: 'REDIRECT_WITH_FILTER',

    LOCATION_REDIRECT: 'LOCATION_REDIRECT',
    SET_IP_DETAILS: 'SET_IP_DETAILS',

    CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE',

    SET_CURRENCY: "SET_CURRENCY",

    SITE_LANGUAGE: "SITE_LANGUAGE",

    SET_SEARCH_COUNTRY: 'SET_SEARCH_COUNTRY'
  },
  cities: {
    GET_ALL_CITIES: 'GET_ALL_CITIES',
    GET_ALL_CITIES_PENDING: 'GET_ALL_CITIES_PENDING',
    GET_ALL_CITIES_SUCCESS: 'GET_ALL_CITIES_SUCCESS',
    GET_ALL_CITIES_ERROR: 'GET_ALL_CITIES_ERROR',

    GET_SELLING_CITIES: "GET_SELLING_CITIES",
    GET_SELLING_CITIES_PENDING: "GET_SELLING_CITIES_PENDING",
    GET_SELLING_CITIES_SUCCESS: "GET_SELLING_CITIES_SUCCESS",
    GET_SELLING_CITIES_ERROR: "GET_SELLING_CITIES_ERROR",

    SELECT_CITY: "SELECT_CITY",

    SET_CITIES: 'SET_CITIES',
  },
  states: {
    GET_ALL_STATES: 'GET_ALL_STATES',
    GET_ALL_STATES_PENDING: 'GET_ALL_STATES_PENDING',
    GET_ALL_STATES_SUCCESS: 'GET_ALL_STATES_SUCCESS',
    GET_ALL_STATES_ERROR: 'GET_ALL_STATES_ERROR',

    GET_SELLING_STATES: "GET_SELLING_STATES",
    GET_SELLING_STATES_PENDING: "GET_SELLING_STATES_PENDING",
    GET_SELLING_STATES_SUCCESS: "GET_SELLING_STATES_SUCCESS",
    GET_SELLING_STATES_ERROR: "GET_SELLING_STATES_ERROR",
  },
  countries: {
    GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
    GET_ALL_COUNTRIES_PENDING: 'GET_ALL_COUNTRIES_PENDING',
    GET_ALL_COUNTRIES_SUCCESS: 'GET_ALL_COUNTRIES_SUCCESS',
    GET_ALL_COUNTRIES_ERROR: 'GET_ALL_COUNTRIES_ERROR',
  },
  common: {
    REMOVE_MY_LISTING: "REMOVE_MY_LISTING",

    GEO_LOCATION: "GEO_LOCATION",

    GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
    GET_ACCESS_TOKEN_PENDING: 'GET_ACCESS_TOKEN_PENDING',
    GET_ACCESS_TOKEN_SUCCESS: 'GET_ACCESS_TOKEN_SUCCESS',
    GET_ACCESS_TOKEN_ERROR: 'GET_ACCESS_TOKEN_ERROR',

    CHECK_USER_EXIST: 'CHECK_USER_EXIST',
    CHECK_USER_EXIST_PENDING: 'CHECK_USER_EXIST_PENDING',
    CHECK_USER_EXIST_SUCCESS: 'CHECK_USER_EXIST_SUCCESS',
    CHECK_USER_EXIST_ERROR: 'CHECK_USER_EXIST_ERROR',

    SEND_OTP: 'SEND_OTP',
    SEND_OTP_PENDING: 'SEND_OTP_PENDING',
    SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS',
    SEND_OTP_ERROR: 'SEND_OTP_ERROR',

    SET_OTP: "SET_OTP",
    SET_MOBILE: "SET_MOBILE",

    OTP_VERIFIED: 'OTP_VERIFIED',
    OTP_VERIFIED_STATUS: 'OTP_VERIFIED_STATUS',

    VERIFY_MOBILE: 'VERIFY_MOBILE',
    VERIFY_MOBILE_PENDING: 'VERIFY_MOBILE_PENDING',
    VERIFY_MOBILE_SUCCESS: 'VERIFY_MOBILE_SUCCESS',
    VERIFY_MOBILE_ERROR: 'VERIFY_MOBILE_ERROR',

    ADD_USER: 'ADD_USER',
    ADD_USER_PENDING: 'ADD_USER_PENDING',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_ERROR: 'ADD_USER_ERROR',

    USER_ADDED: 'USER_ADDED',

    RESET_PASSWORD: "RESET_PASSWORD",

    LOGIN: 'LOGIN',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    RFP_LOGIN: "RFP_LOGIN",

    GET_USER_PROFILE: 'GET_USER_PROFILE',
    GET_USER_PROFILE_PENDING: 'GET_USER_PROFILE_PENDING',
    GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
    GET_USER_PROFILE_ERROR: 'GET_USER_PROFILE_ERROR',

    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_USER_PROFILE_PENDING: 'UPDATE_USER_PROFILE_PENDING',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_ERROR: 'UPDATE_USER_PROFILE_ERROR',

    UPDATE_LANGUAGE: "UPDATE_LANGUAGE",
    UPDATE_LANGUAGE_PENDING: "UPDATE_LANGUAGE_PENDING",
    UPDATE_LANGUAGE_SUCCESS: "UPDATE_LANGUAGE_SUCCESS",
    UPDATE_LANGUAGE_ERROR: "UPDATE_LANGUAGE_ERROR",

    LOGOUT: 'LOGOUT',
    LOGOUT_PENDING: 'LOGOUT_PENDING',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    FORGET_PASSWORD: 'FORGET_PASSWORD',
    FORGET_PASSWORD_PENDING: 'FORGET_PASSWORD_PENDING',
    FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
    FORGET_PASSWORD_ERROR: 'FORGET_PASSWORD_ERROR',

    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_PASSWORD_PENDING: 'UPDATE_PASSWORD_PENDING',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_ERROR: 'UPDATE_PASSWORD_ERROR',

    UPDATE_NEW_PASSWORD: 'UPDATE_NEW_PASSWORD',
    UPDATE_NEW_PASSWORD_PENDING: 'UPDATE_NEW_PASSWORD_PENDING',
    UPDATE_NEW_PASSWORD_SUCCESS: 'UPDATE_NEW_PASSWORD_SUCCESS',
    UPDATE_NEW_PASSWORD_ERROR: 'UPDATE_NEW_PASSWORD_ERROR',

    SET_USER_TYPE: 'SET_USER_TYPE',

    GET_SUBSCRPTION_PLAN: 'GET_SUBSCRPTION_PLAN',
    GET_SUBSCRPTION_PLAN_PENDING: 'GET_SUBSCRPTION_PLAN_PENDING',
    GET_SUBSCRPTION_PLAN_SUCCESS: 'GET_SUBSCRPTION_PLAN_SUCCESS',
    GET_SUBSCRPTION_PLAN_ERROR: 'GET_SUBSCRPTION_PLAN_ERROR',

    GET_REFERRAL_CODE: 'GET_REFERRAL_CODE',
    GET_REFERRAL_CODE_PENDING: 'GET_REFERRAL_CODE_PENDING',
    GET_REFERRAL_CODE_SUCCESS: 'GET_REFERRAL_CODE_SUCCESS',
    GET_REFERRAL_CODE_ERROR: 'GET_REFERRAL_CODE_ERROR',
    
    SELECTED_TAB: "SELECTED_TAB",
    SELECTED_TAB_BP: "SELECTED_TAB_BP",

    VERIFY_EMAIL: 'VERIFY_EMAIL',
    VERIFY_EMAIL_PENDING: 'VERIFY_EMAIL_PENDING',
    VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
    VERIFY_EMAIL_ERROR: 'VERIFY_EMAIL_ERROR',

    CLEAR_DATA: "CLEAR_DATA",
    SET_LANG: "SET_LANG",
    RESET_USER: "RESET_USER",

    DELETE_ACCOUNT: "DELETE_ACCOUNT",
    DELETE_ACCOUNT_PENDING: "DELETE_ACCOUNT_PENDING",
    DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
    DELETE_ACCOUNT_ERROR: "DELETE_ACCOUNT_ERROR",

    ACTIVATE_ACCOUNT: "ACTIVATE_ACCOUNT",

    VERIFY_USER_EMAIL: 'VERIFY_USER_EMAIL',
    VERIFY_USER_EMAIL_PENDING: 'VERIFY_USER_EMAIL_PENDING',
    VERIFY_USER_EMAIL_SUCCESS: 'VERIFY_USER_EMAIL_SUCCESS',
    VERIFY_USER_EMAIL_ERROR: 'VERIFY_USER_EMAIL_ERROR',
  },
  seller: {
    SET_SELLER_MOBILE: 'SET_SELLER_MOBILE',

    GET_SELLER_PROFILE: 'GET_SELLER_PROFILE',
    GET_SELLER_PROFILE_PENDING: 'GET_SELLER_PROFILE_PENDING',
    GET_SELLER_PROFILE_SUCCESS: 'GET_SELLER_PROFILE_SUCCESS',
    GET_SELLER_PROFILE_ERROR: 'GET_SELLER_PROFILE_ERROR',

    UPDATE_SELLER_PROFILE: 'UPDATE_SELLER_PROFILE',
    UPDATE_SELLER_PROFILE_PENDING: 'UPDATE_SELLER_PROFILE_PENDING',
    UPDATE_SELLER_PROFILE_SUCCESS: 'UPDATE_SELLER_PROFILE_SUCCESS',
    UPDATE_SELLER_PROFILE_ERROR: 'UPDATE_SELLER_PROFILE_ERROR',

    VERIFY_SELLER_EMAIL: 'VERIFY_SELLER_EMAIL',
    VERIFY_SELLER_EMAIL_PENDING: 'VERIFY_SELLER_EMAIL_PENDING',
    VERIFY_SELLER_EMAIL_SUCCESS: 'VERIFY_SELLER_EMAIL_SUCCESS',
    VERIFY_SELLER_EMAIL_ERROR: 'VERIFY_SELLER_EMAIL_ERROR',

    SELLER_EMAIL_VERIFIED: 'SELLER_EMAIL_VERIFIED',
    SELLER_EMAIL_VERIFIED_PENDING: 'SELLER_EMAIL_VERIFIED_PENDING',
    SELLER_EMAIL_VERIFIED_SUCCESS: 'SELLER_EMAIL_VERIFIED_SUCCESS',
    SELLER_EMAIL_VERIFIED_ERROR: 'SELLER_EMAIL_VERIFIED_ERROR',

    GET_SELLER_NOTIFICATION: 'GET_SELLER_NOTIFICATION',
    GET_SELLER_NOTIFICATION_PENDING: 'GET_SELLER_NOTIFICATION_PENDING',
    GET_SELLER_NOTIFICATION_SUCCESS: 'GET_SELLER_NOTIFICATION_SUCCESS',
    GET_SELLER_NOTIFICATION_ERROR: 'GET_SELLER_NOTIFICATION_ERROR',

    UPDATE_SELLER_NOTIFICATION: 'UPDATE_SELLER_NOTIFICATION',
    UPDATE_SELLER_NOTIFICATION_PENDING: 'UPDATE_SELLER_NOTIFICATION_PENDING',
    UPDATE_SELLER_NOTIFICATION_SUCCESS: 'UPDATE_SELLER_NOTIFICATION_SUCCESS',
    UPDATE_SELLER_NOTIFICATION_ERROR: 'UPDATE_SELLER_NOTIFICATION_ERROR',

    EDIT_PRODUCT_INFO: 'EDIT_PRODUCT_INFO',

    DELETE_SELLER_PRODUCT: 'DELETE_SELLER_PRODUCT',
    DELETE_SELLER_PRODUCT_PENDING: 'DELETE_SELLER_PRODUCT_PENDING',
    DELETE_SELLER_PRODUCT_SUCCESS: 'DELETE_SELLER_PRODUCT_SUCCESS',
    DELETE_SELLER_PRODUCT_ERROR: 'DELETE_SELLER_PRODUCT_ERROR',

    PRODUCT_SELECTION: 'PRODUCT_SELECTION',

    ADD_SELECTED_PRODUCTS: "ADD_SELECTED_PRODUCTS",
    ADD_SELECTED_PRODUCTS_PENDING: 'ADD_SELECTED_PRODUCTS_PENDING',
    ADD_SELECTED_PRODUCTS_SUCCESS: 'ADD_SELECTED_PRODUCTS_SUCCESS',
    ADD_SELECTED_PRODUCTS_ERROR: 'ADD_SELECTED_PRODUCTS_ERROR',

    UPDATE_SELLER_PRODUCT: "UPDATE_SELLER_PRODUCT",
    UPDATE_SELLER_PRODUCT_PENDING: 'UPDATE_SELLER_PRODUCT_PENDING',
    UPDATE_SELLER_PRODUCT_SUCCESS: 'UPDATE_SELLER_PRODUCT_SUCCESS',
    UPDATE_SELLER_PRODUCT_ERROR: 'UPDATE_SELLER_PRODUCT_ERROR',

    GET_SELLER_PRODUCT: "GET_SELLER_PRODUCT",
    GET_SELLER_PRODUCT_PENDING: "GET_SELLER_PRODUCT_PENDING",
    GET_SELLER_PRODUCT_SUCCESS: "GET_SELLER_PRODUCT_SUCCESS",
    GET_SELLER_PRODUCT_ERROR: "GET_SELLER_PRODUCT_ERROR",

    GET_FILTERED_CITIES: "GET_FILTERED_CITIES",
    GET_FILTERED_CITIES_PENDING: "GET_FILTERED_CITIES_PENDING",
    GET_FILTERED_CITIES_SUCCESS: "GET_FILTERED_CITIES_SUCCESS",
    GET_FILTERED_CITIES_ERROR: "GET_FILTERED_CITIES_ERROR",

    UPDATE_STATUS: "UPDATE_STATUS",

    GET_BUYER_ENQUIRIES: 'GET_BUYER_ENQUIRIES',
    GET_BUYER_ENQUIRIES_PENDING: 'GET_BUYER_ENQUIRIES_PENDING',
    GET_BUYER_ENQUIRIES_SUCCESS: 'GET_BUYER_ENQUIRIES_SUCCESS',
    GET_BUYER_ENQUIRIES_ERROR: 'GET_BUYER_ENQUIRIES_ERROR',

    ACTIVATE_TRIAL_PLAN: "ACTIVATE_TRIAL_PLAN",
    ACTIVATE_TRIAL_PLAN_PENDING: "ACTIVATE_TRIAL_PLAN_PENDING",
    ACTIVATE_TRIAL_PLAN_ERROR: "ACTIVATE_TRIAL_PLAN_ERROR",
    ACTIVATE_TRIAL_PLAN_SUCCESS: "ACTIVATE_TRIAL_PLAN_SUCCESS",

    SET_SUBSCRIPTION_ID: 'SET_SUBSCRIPTION_ID',
    CLEAR_SUBSCRIPTION_ID: 'CLEAR_SUBSCRIPTION_ID',

    CREATE_ORDERS_ID: 'CREATE_ORDERS_ID',
    CREATE_ORDERS_ID_PENDING: 'CREATE_ORDERS_ID_PENDING',
    CREATE_ORDERS_ID_SUCCESS: 'CREATE_ORDERS_ID_SUCCESS',
    CREATE_ORDERS_ID_ERROR: 'CREATE_ORDERS_ID_ERROR',

    CREATE_PAYMENT_ID: 'CREATE_PAYMENT_ID',
    CREATE_PAYMENT_ID_PENDING: 'CREATE_PAYMENT_ID_PENDING',
    CREATE_PAYMENT_ID_SUCCESS: 'CREATE_PAYMENT_ID_SUCCESS',
    CREATE_PAYMENT_ID_ERROR: 'CREATE_PAYMENT_ID_ERROR',

    CAPTURE_ORDER: 'CAPTURE_ORDER',
    CAPTURE_ORDER_PENDING: 'CAPTURE_ORDER_PENDING',
    CAPTURE_ORDER_SUCCESS: 'CAPTURE_ORDER_SUCCESS',
    CAPTURE_ORDER_ERROR: 'CAPTURE_ORDER_ERROR',

    CAPTURE_SUBSCRIPTION: 'CAPTURE_SUBSCRIPTION',
    CAPTURE_SUBSCRIPTION_PENDING: 'CAPTURE_SUBSCRIPTION_PENDING',
    CAPTURE_SUBSCRIPTION_SUCCESS: 'CAPTURE_SUBSCRIPTION_SUCCESS',
    CAPTURE_SUBSCRIPTION_ERROR: 'CAPTURE_SUBSCRIPTION_ERROR',

    GET_ORDERS: 'GET_ORDERS',
    GET_ORDERS_PENDING: 'GET_ORDERS_PENDING',
    GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
    GET_ORDERS_ERROR: 'GET_ORDERS_ERROR',

    DELETE_SELLER_DOC: 'DELETE_SELLER_DOC',
    DELETE_SELLER_DOC_PENDING: 'DELETE_SELLER_DOC_PENDING',
    DELETE_SELLER_DOC_SUCCESS: 'DELETE_SELLER_DOC_SUCCESS',
    DELETE_SELLER_DOC_ERROR: 'DELETE_SELLER_DOC_ERROR',

    GET_ALL_OFFERS: "GET_ALL_OFFERS",
    GET_ALL_OFFERS_PENDING: "GET_ALL_OFFERS_PENDING",
    GET_ALL_OFFERS_SUCCESS: "GET_ALL_OFFERS_SUCCESS",
    GET_ALL_OFFERS_ERROR: "GET_ALL_OFFERS_ERROR",

    GET_SELLER_OFFERS: "GET_SELLER_OFFERS",
    GET_SELLER_OFFERS_PENDING: "GET_SELLER_OFFERS_PENDING",
    GET_SELLER_OFFERS_SUCCESS: "GET_SELLER_OFFERS_SUCCESS",
    GET_SELLER_OFFERS_ERROR: "GET_SELLER_OFFERS_ERROR",

    POST_SELLER_CONTACT_OFFERS: "POST_SELLER_CONTACT_OFFERS",
    POST_SELLER_CONTACT_OFFERS_PENDING: "POST_SELLER_CONTACT_OFFERS_PENDING",
    POST_SELLER_CONTACT_OFFERS_SUCCESS: "POST_SELLER_CONTACT_OFFERS_SUCCESS",
    POST_SELLER_CONTACT_OFFERS_ERROR: "POST_SELLER_CONTACT_OFFERS_ERROR",

    CANCEL_SUBSCRIPTION: "CANCEL_SUBSCRIPTION",
    CANCEL_SUBSCRIPTION_PENDING: "CANCEL_SUBSCRIPTION_PENDING",
    CANCEL_SUBSCRIPTION_SUCCESS: "CANCEL_SUBSCRIPTION_SUCCESS",
    CANCEL_SUBSCRIPTION_ERROR: "CANCEL_SUBSCRIPTION_ERROR",
  },

  buyer: {
    SET_BUYER_MOBILE: 'SET_BUYER_MOBILE',

    POST_RFP: 'POST_RFP',
    POST_RFP_PENDING: 'POST_RFP_PENDING',
    POST_RFP_SUCCESS: 'POST_RFP_SUCCESS',
    POST_RFP_ERROR: 'POST_RFP_ERROR',

    GET_BUYER_PROFILE: 'GET_BUYER_PROFILE',
    GET_BUYER_PROFILE_PENDING: 'GET_BUYER_PROFILE_PENDING',
    GET_BUYER_PROFILE_SUCCESS: 'GET_BUYER_PROFILE_SUCCESS',
    GET_BUYER_PROFILE_ERROR: 'GET_BUYER_PROFILE_ERROR',

    UPDATE_BUYER_PROFILE: 'UPDATE_BUYER_PROFILE',
    UPDATE_BUYER_PROFILE_PENDING: 'UPDATE_BUYER_PROFILE_PENDING',
    UPDATE_BUYER_PROFILE_SUCCESS: 'UPDATE_BUYER_PROFILE_SUCCESS',
    UPDATE_BUYER_PROFILE_ERROR: 'UPDATE_BUYER_PROFILE_ERROR',

    VERIFY_BUYER_EMAIL: 'VERIFY_BUYER_EMAIL',
    VERIFY_BUYER_EMAIL_PENDING: 'VERIFY_BUYER_EMAIL_PENDING',
    VERIFY_BUYER_EMAIL_SUCCESS: 'VERIFY_BUYER_EMAIL_SUCCESS',
    VERIFY_BUYER_EMAIL_ERROR: 'VERIFY_BUYER_EMAIL_ERROR',

    BUYER_EMAIL_VERIFIED: 'BUYER_EMAIL_VERIFIED',
    BUYER_EMAIL_VERIFIED_PENDING: 'BUYER_EMAIL_VERIFIED_PENDING',
    BUYER_EMAIL_VERIFIED_SUCCESS: 'BUYER_EMAIL_VERIFIED_SUCCESS',
    BUYER_EMAIL_VERIFIED_ERROR: 'BUYER_EMAIL_VERIFIED_ERROR',

    GET_BUYER_NOTIFICATION: 'GET_BUYER_NOTIFICATION',
    GET_BUYER_NOTIFICATION_PENDING: 'GET_BUYER_NOTIFICATION_PENDING',
    GET_BUYER_NOTIFICATION_SUCCESS: 'GET_BUYER_NOTIFICATION_SUCCESS',
    GET_BUYER_NOTIFICATION_ERROR: 'GET_BUYER_NOTIFICATION_ERROR',

    UPDATE_BUYER_NOTIFICATION: 'UPDATE_BUYER_NOTIFICATION',
    UPDATE_BUYER_NOTIFICATION_PENDING: 'UPDATE_BUYER_NOTIFICATION_PENDING',
    UPDATE_BUYER_NOTIFICATION_SUCCESS: 'UPDATE_BUYER_NOTIFICATION_SUCCESS',
    UPDATE_BUYER_NOTIFICATION_ERROR: 'UPDATE_BUYER_NOTIFICATION_ERROR',

    GET_ALL_BUYERS: 'GET_ALL_BUYERS',
    GET_ALL_BUYERS_PENDING: 'GET_ALL_BUYERS_PENDING',
    GET_ALL_BUYERS_SUCCESS: 'GET_ALL_BUYERS_SUCCESS',
    GET_ALL_BUYERS_ERROR: 'GET_ALL_BUYERS_ERROR',

    GET_BUYER_REQUEST: "GET_BUYER_REQUEST",
    GET_BUYER_REQUEST_PENDING: "GET_BUYER_REQUEST_PENDING",
    GET_BUYER_REQUEST_SUCCESS: "GET_BUYER_REQUEST_SUCCESS",
    GET_BUYER_REQUEST_ERROR: "GET_BUYER_REQUEST_ERROR",

    POST_BUYER_REQUEST: "POST_BUYER_REQUEST",
    POST_BUYER_REQUEST_PENDING: "POST_BUYER_REQUEST_PENDING",
    POST_BUYER_REQUEST_SUCCESS: "POST_BUYER_REQUEST_SUCCESS",
    POST_BUYER_REQUEST_ERROR: "POST_BUYER_REQUEST_ERROR",

    GET_ALL_BUYER_REQUEST: "GET_ALL_BUYER_REQUEST",
    GET_ALL_BUYER_REQUEST_PENDING: "GET_ALL_BUYER_REQUEST_PENDING",
    GET_ALL_BUYER_REQUEST_SUCCESS: "GET_ALL_BUYER_REQUEST_SUCCESS",
    GET_ALL_BUYER_REQUEST_ERROR: "GET_ALL_BUYER_REQUEST_ERROR",

    DELETE_BUYER_REQUEST: "DELETE_BUYER_REQUEST",
    DELETE_BUYER_REQUEST_PENDING: "DELETE_BUYER_REQUEST_PENDING",
    DELETE_BUYER_REQUEST_SUCCESS: "DELETE_BUYER_REQUEST_SUCCESS",
    DELETE_BUYER_REQUEST_ERROR: "DELETE_BUYER_REQUEST_ERROR",
  },
  categories: {
    GET_SPECIFIC: "GET_SPECIFIC",
    GET_SPECIFIC_PENDING: 'GET_SPECIFIC_PENDING',
    GET_SPECIFIC_SUCCESS: 'GET_SPECIFIC_SUCCESS',
    GET_SPECIFIC_ERROR: 'GET_SPECIFIC_ERROR',

    GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
    GET_ALL_CATEGORIES_PENDING: 'GET_ALL_CATEGORIES_PENDING',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_ERROR: 'GET_ALL_CATEGORIES_ERROR',

    GET_CATEGORY: 'GET_CATEGORY',
    GET_CATEGORY_PENDING: 'GET_CATEGORY_PENDING',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_ERROR: 'GET_CATEGORY_ERROR',

    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_ALL_PRODUCTS_PENDING: 'GET_ALL_PRODUCTS_PENDING',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_ERROR: 'GET_ALL_PRODUCTS_ERROR',

    GET_SELLER_TYPES: 'GET_SELLER_TYPES',
    GET_SELLER_TYPES_PENDING: 'GET_SELLER_TYPES_PENDING',
    GET_SELLER_TYPES_SUCCESS: 'GET_SELLER_TYPES_SUCCESS',
    GET_SELLER_TYPES_ERROR: 'GET_SELLER_TYPES_ERROR',

    SET_SEARCH_KEYWORD: "SET_SEARCH_KEYWORD",

    GET_SECONDARY_CATEGORIES: "GET_SECONDARY_CATEGORIES",
    GET_SECONDARY_CATEGORIES_PENDING: 'GET_SECONDARY_CATEGORIES_PENDING',
    GET_SECONDARY_CATEGORIES_SUCCESS: 'GET_SECONDARY_CATEGORIES_SUCCESS',
    GET_SECONDARY_CATEGORIES_ERROR: 'GET_SECONDARY_CATEGORIES_ERROR',

    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_PENDING: 'GET_PRODUCTS_PENDING',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',

    GET_PRIMARY_CATEGORY: "GET_PRIMARY_CATEGORY",
    GET_PRIMARY_CATEGORY_PENDING: 'GET_PRIMARY_CATEGORY_PENDING',
    GET_PRIMARY_CATEGORY_SUCCESS: 'GET_PRIMARY_CATEGORY_SUCCESS',
    GET_PRIMARY_CATEGORY_ERROR: 'GET_PRIMARY_CATEGORY_ERROR',

    SELECTED_L2: "SELECTED_L2",

    GET_ALL_LEVEL5_PRODUCTS: 'GET_ALL_LEVEL5_PRODUCTS',
    GET_ALL_LEVEL5_PRODUCTS_PENDING: 'GET_ALL_LEVEL5_PRODUCTS_PENDING',
    GET_ALL_LEVEL5_PRODUCTS_SUCCESS: 'GET_ALL_LEVEL5_PRODUCTS_SUCCESS',
    GET_ALL_LEVEL5_PRODUCTS_ERROR: 'GET_ALL_LEVEL5_PRODUCTS_ERROR',

  },
  search: {
    SEARCH: "SEARCH",
    SEARCH_PENDING: 'SEARCH_PENDING',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_ERROR: 'SEARCH_ERROR',

    GET_ALL_SELLERS: 'GET_ALL_SELLERS',
    GET_ALL_SELLERS_PENDING: 'GET_ALL_SELLERS_PENDING',
    GET_ALL_SELLERS_SUCCESS: 'GET_ALL_SELLERS_SUCCESS',
    GET_ALL_SELLERS_ERROR: 'GET_ALL_SELLERS_ERROR',

    ALL_CITY: "ALL_CITY",

    ACTIVE_SELLER_NUMBERS: "ACTIVE_SELLER_NUMBERS",
    ACTIVE_SELLER_COUNT: "ACTIVE_SELLER_COUNT",
    SET_ACTIVE_NUMBER: "SET_ACTIVE_NUMBER"
  },
  contactUs: {
    POST_CONTACTUS: 'POST_CONTACTUS',
    POST_CONTACTUS_PENDING: 'POST_CONTACTUS_PENDING',
    POST_CONTACTUS_SUCCESS: 'POST_CONTACTUS_SUCCESS',
    POST_CONTACTUS_ERROR: 'POST_CONTACTUS_ERROR',
  },
  removeListing: {
    POST_REMOVELISTING: 'POST_REMOVELISTING',
    POST_REMOVELISTING_PENDING: 'POST_REMOVELISTING_PENDING',
    POST_REMOVELISTING_SUCCESS: 'POST_REMOVELISTING_SUCCESS',
    POST_REMOVELISTING_ERROR: 'POST_REMOVELISTING_ERROR',
  },
  chat: {

    CHAT_OPEN: "CHAT_OPEN",
    CHAT_CLOSE: "CHAT_CLOSE",
    CHAT_RESET: "CHAT_RESET",
    CHAT_WHOSE_HISTORY: "CHAT_WHOSE_HISTORY",
    CHAT_RESET_LIST: "CHAT_RESET_LIST",

    CHAT_SET_HISTORY_LIMIT: "CHAT_SET_HISTORY_LIMIT",

    CHAT_CONNECT: "CHAT_CONNECT",
    CHAT_LOGIN: "CHAT_LOGIN",
    CHAT_SUBSCRIBE: "CHAT_SUBSCRIBE",

    CHAT_SOCKET_LIST: "CHAT_SOCKET_LIST",

    CHAT_ROOM_ID: 'CHAT_ROOM_ID',
    CHAT_STEP: 'CHAT_ROOM_ID',

    CHAT_LANGUAGE_SET: 'CHAT_LANGUAGE_SET',
    CHAT_LANGUAGE_SET_PENDING: 'CHAT_LANGUAGE_SET_PENDING',
    CHAT_LANGUAGE_SET_SUCCESS: 'CHAT_LANGUAGE_SET_SUCCESS',
    CHAT_LANGUAGE_SET_ERROR: 'CHAT_LANGUAGE_SET_ERROR',

    CHAT_LOGIN: 'CHAT_LOGIN',
    CHAT_LOGIN_PENDING: 'CHAT_LOGIN_PENDING',
    CHAT_LOGIN_SUCCESS: 'CHAT_LOGIN_SUCCESS',
    CHAT_LOGIN_ERROR: 'CHAT_LOGIN_ERROR',

    CHAT_REGISTER: 'CHAT_REGISTER',
    CHAT_REGISTER_PENDING: 'CHAT_REGISTER_PENDING',
    CHAT_REGISTER_SUCCESS: 'CHAT_REGISTER_SUCCESS',
    CHAT_REGISTER_ERROR: 'CHAT_REGISTER_ERROR',

    CHAT_GET_LIST: 'CHAT_GET_LIST',
    CHAT_GET_LIST_PENDING: 'CHAT_GET_LIST_PENDING',
    CHAT_GET_LIST_SUCCESS: 'CHAT_GET_LIST_SUCCESS',
    CHAT_GET_LIST_ERROR: 'CHAT_GET_LIST_ERROR',

    CHAT_GET_HISTORY: 'CHAT_GET_HISTORY',
    CHAT_GET_HISTORY_PENDING: 'CHAT_GET_HISTORY_PENDING',
    CHAT_GET_HISTORY_SUCCESS: 'CHAT_GET_HISTORY_SUCCESS',
    CHAT_GET_HISTORY_ERROR: 'CHAT_GET_HISTORY_ERROR',

    CHAT_HISTORY_RESET: 'CHAT_HISTORY_RESET',

    CHAT_ROOM_OPEN: 'CHAT_ROOM_OPEN',
    CHAT_ROOM_OPEN_PENDING: 'CHAT_ROOM_OPEN_PENDING',
    CHAT_ROOM_OPEN_SUCCESS: 'CHAT_ROOM_OPEN_SUCCESS',
    CHAT_ROOM_OPEN_ERROR: 'CHAT_ROOM_OPEN_ERROR',

    CHAT_SEND_MESSAGE: 'CHAT_SEND_MESSAGE',
    CHAT_SEND_MESSAGE_PENDING: 'CHAT_SEND_MESSAGE_PENDING',
    CHAT_SEND_MESSAGE_SUCCESS: 'CHAT_SEND_MESSAGE_SUCCESS',
    CHAT_SEND_MESSAGE_ERROR: 'CHAT_SEND_MESSAGE_ERROR',

    CHAT_MARK_AS_READ_MESSAGE: 'CHAT_MARK_AS_READ_MESSAGE',
    CHAT_MARK_AS_READ_MESSAGE_PENDING: 'CHAT_MARK_AS_READ_MESSAGE_PENDING',
    CHAT_MARK_AS_READ_MESSAGE_SUCCESS: 'CHAT_MARK_AS_READ_MESSAGE_SUCCESS',
    CHAT_MARK_AS_READ_MESSAGE_ERROR: 'CHAT_MARK_AS_READ_MESSAGE_ERROR',


    CHAT_GET_SELLER_DETAILS: 'CHAT_GET_SELLER_DETAILS',
    CHAT_GET_SELLER_DETAILS_PENDING: 'CHAT_GET_SELLER_DETAILS_PENDING',
    CHAT_GET_SELLER_DETAILS_SUCCESS: 'CHAT_GET_SELLER_DETAILS_SUCCESS',
    CHAT_GET_SELLER_DETAILS_ERROR: 'CHAT_GET_SELLER_DETAILS_ERROR',

    CHAT_LOGOUT: 'CHAT_LOGOUT',
    CHAT_LOGOUT_PENDING: 'CHAT_LOGOUT_PENDING',
    CHAT_LOGOUT_SUCCESS: 'CHAT_LOGOUT_SUCCESS',
    CHAT_LOGOUT_ERROR: 'CHAT_LOGOUT_ERROR',

    CHAT_CATEGORY: 'CHAT_CATEGORY',
    CHAT_CATEGORY_RESET: 'CHAT_CATEGORY_RESET',

    GET_ALL_CHAT_TEMPLATES: 'GET_ALL_CHAT_TEMPLATES',
    GET_ALL_CHAT_TEMPLATES_PENDING: 'GET_ALL_CHAT_TEMPLATES_PENDING',
    GET_ALL_CHAT_TEMPLATES_SUCCESS: 'GET_ALL_CHAT_TEMPLATES_SUCCESS',
    GET_ALL_CHAT_TEMPLATES_ERROR: 'GET_ALL_CHAT_TEMPLATES_ERROR',

    CHAT_CATEGORY_HEIGHT:"CHAT_CATEGORY_HEIGHT",

  },
  commodities: {
    GET_COMMODITIES: 'GET_COMMODITIES',
    GET_COMMODITIES_PENDING: 'GET_COMMODITIES_PENDING',
    GET_COMMODITIES_SUCCESS: 'GET_COMMODITIES_SUCCESS',
    GET_COMMODITIES_ERROR: 'GET_COMMODITIES_ERROR',
    GET_NEWS: 'GET_NEWS',
    GET_NEWS_PENDING: 'GET_NEWS_PENDING',
    GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
    GET_NEWS_ERROR: 'GET_NEWS_ERROR',
  }
}

export const QS = {
  tender: {
    tenderValueRange: 'tenderValueRange',
  },
}
