export const categoriesOptions = [
    { value: "Cerals And Pulses", label: "Cerals And Pulses", commodity: 1 },
    { value: "Oil And Oil Seeds", label: "Oil And Oil Seeds", commodity: 2 },
    { value: "Fibres", label: "Fibres", commodity: 3 },
    { value: "Soft", label: "Soft", commodity: 4 },
    { value: "Spices", label: "Spices", commodity: 5 },
    { value: "Guar Complex", label: "Guar Complex", commodity: 6 },
    { value: "Index Products", label: "Index Products", commodity: 7 },
    { value: "Metals", label: "Metals", commodity: 8 },

    // 18-05-2022
    { value: "Vegetables", label: "Vegetables", commodity: 9 },
    { value: "Others", label: "Others", commodity: 10 },
    { value: "Metals", label: "Metals", commodity: 11 },

]

export const commodityOptions = [
    { value: "Chana", label: "Chana", veriety: 1 },
    { value: "Barley", label: "Barley", veriety: 2 },
    { value: "Bajra", label: "Bajra", veriety: 3 },
    { value: "Wheat", label: "Wheat", veriety: 4 },
    { value: "Moong", label: "Moong", veriety: 5 },
    { value: "Maize Feed industrial Grade", label: "Maize Feed industrial Grade", veriety: 6 },
    { value: "Paddy (Basmati) - Pusa 1121", label: "Paddy (Basmati) - Pusa 1121", veriety: 7 },

    { value: "Castor Seed", label: "Castor Seed", veriety: 8 },
    { value: "Cotton Seed Oilcake", label: "Cotton Seed Oilcake", veriety: 9 },
    { value: "Soybean", label: "Soybean", veriety: 10 },
    { value: "Refined Soy Oil", label: "Refined Soy Oil", veriety: 11 },
    { value: "Mustard Seed", label: "Mustard Seed", veriety: 12 },
    { value: "Crude Palm Oil", label: "Crude Palm Oil", veriety: 13 },
    { value: "Natural Whittish Sesame Seeds", label: "Natural Whittish Sesame Seeds", veriety: 14 },
    { value: "Hipro Soybean Meal", label: "Hipro Soybean Meal", veriety: 15 },

    { value: "Kapas", label: "Kapas", veriety: 16 },
    { value: "29 mm Cotton", label: "29 mm Cotton", veriety: 17 },
    { value: "Gur (Feed Grade)", label: "Gur (Feed Grade)", veriety: 18 },

    { value: "Turmeric", label: "Turmeric", veriety: 19 },
    { value: "Coriander", label: "Coriander", veriety: 23 },
    // { value: "Jeera", label: "Jeera", veriety: 21 },
    { value: "Ginger", label: "Ginger", veriety: 20 },
    { value: "Garlic", label: "Garlic", veriety: 21 },
    { value: "Green Chilli", label: "Green Chilli", veriety: 22 },
    { value: "Copra", label: "Copra", veriety: 24 },
    { value: "Pepper", label: "Pepper", veriety: 25 },
    { value: "Cardamom (S)", label: "Cardamom (S)", veriety: 26 },
    { value: "Cocoa", label: "Cocoa", veriety: 27 },
    { value: "Vanilla", label: "Vanilla", veriety: 28 },
    { value: "Star Aniseed", label: "Star Aniseed", veriety: 29 },
    { value: "Cumin Seeds", label: "Cumin Seeds", veriety: 30 },
    { value: "Mustard", label: "Mustard", veriety: 31 },
    { value: "Sesame", label: "Sesame", veriety: 32 },
    { value: "Fenugreek", label: "Fenugreek", veriety: 33 },
    { value: "Asafoetida", label: "Asafoetida", veriety: 34 },
    { value: "Red Dry Chilli", label: "Red Dry Chilli", veriety: 35 },
    { value: "Aniseed", label: "Aniseed", veriety: 36 },
    { value: "Cinnamon", label: "Cinnamon", veriety: 37 },
    { value: "Cloves", label: "Cloves", veriety: 38 },
    { value: "Pomegranate Seeds", label: "Pomegranate Seeds", veriety: 39 },
    { value: "Bay Leaf", label: "Bay Leaf", veriety: 40 },
    { value: "Lemon Grass", label: "Lemon Grass", veriety: 41 },
    { value: "Soya", label: "Soya", veriety: 42 },
    { value: "Onion", label: "Onion", veriety: 43 },

    { value: "Guar Seed 10 mt", label: "Guar Seed 10 mt", veriety: 45 },
    { value: "Gaur Gum Refined Splits", label: "Gaur Gum Refined Splits", veriety: 46 },

    { value: "Agridex", label: "Agridex", veriety: 47 },
    { value: "Guarex", label: "Guarex", veriety: 48 },

    { value: "Steel Long", label: "Steel Long", veriety: 49 },

    // Suman Changes
    { value: "Moth Beans/ Matki", label: "Moth Beans/ Matki", veriety: 50 },
    { value: "Wheat Grains", label: "Wheat Grains", veriety: 51 },
    { value: "Millet", label: "Millet", veriety: 52 },
    { value: "Dry beans", label: "Dry beans", veriety: 53 },
    { value: "Dry board beans", label: "Dry board beans", veriety: 54 },
    { value: "Dry peas", label: "Dry peas", veriety: 55 },
    { value: "Curry Leaves", label: "Curry Leaves", veriety: 56 },
    { value: "Tomato", label: "Tomato", veriety: 57 },
    { value: "Brinjal", label: "Brinjal", veriety: 58 },
    { value: "Potato", label: "Potato", veriety: 59 },
    { value: "Drumstick", label: "Drumstick", veriety: 60 },
    { value: "Beetroot", label: "Beetroot", veriety: 61 },
    { value: "Carrot", label: "Carrot", veriety: 62 },
    { value: "Mint", label: "Mint", veriety: 63 },
    { value: "Pumpkin", label: "Pumpkin", veriety: 64 },
    { value: "Radish", label: "Radish", veriety: 65 },
    { value: "Cucumber", label: "Cucumber", veriety: 66 },
    { value: "Pointed Gourd", label: "Pointed Gourd", veriety: 67 },
    { value: "Capsicum", label: "Capsicum", veriety: 68 },
    { value: "Broad Beans", label: "Broad Beans", veriety: 69 },
    { value: "Cluster Beans", label: "Cluster Beans", veriety: 70 },
    { value: "French Beans", label: "French Beans", veriety: 71 },
    { value: "Lemon", label: "Lemon", veriety: 72 },
    { value: "Cabbage", label: "Cabbage", veriety: 73 },
    { value: "Cauliflower", label: "Cauliflower", veriety: 74 },
    { value: "Bitter Gourd", label: "Bitter Gourd", veriety: 75 },
    { value: "Bottle Gourd", label: "Bottle Gourd", veriety: 76 },
    { value: "Ivy Gourd", label: "Ivy Gourd", veriety: 77 },
    { value: "Raw Banana", label: "Raw Banana", veriety: 78 },
    { value: "Turnip", label: "Turnip", veriety: 79 },
    { value: "Green Peas", label: "Green Peas", veriety: 80 },
    { value: "Cowpeas", label: "Cowpeas", veriety: 81 },
    { value: "Corn", label: "Corn", veriety: 82 },
    { value: "Sweet Potatoes", label: "Sweet Potatoes", veriety: 83 },
    { value: "Spinach", label: "Spinach", veriety: 84 },
    { value: "Mango (Raw)", label: "Mango (Raw)", veriety: 85 },
    { value: "Okra (Lady Finger)", label: "Okra (Lady Finger)", veriety: 86 },
    { value: "Papaya (Raw)", label: "Papaya (Raw)", veriety: 87 },
    { value: "Jackfruit (Raw)", label: "Jackfruit (Raw)", veriety: 88 },
    { value: "Indian Gooseberry", label: "Indian Gooseberry", veriety: 89 },
    { value: "Indian Squash", label: "Indian Squash", veriety: 90 },
    { value: "Dill", label: "Dill", veriety: "91" },
    { value: "Amaranth", label: "Amaranth", veriety: 92 },
    { value: "Mango", label: "Mango", veriety: 93 },
    { value: "Apple", label: "Apple", veriety: 94 },
    { value: "Grapes", label: "Grapes", veriety: 95 },
    { value: "Guava", label: "Guava", veriety: 96 },
    { value: "Musk Melon", label: "Musk Melon", veriety: 97 },
    { value: "Banana", label: "Banana", veriety: 98 },
    { value: "Orange", label: "Orange", veriety: 99 },
    { value: "Water melon", label: "Water melon", veriety: 100 },
    { value: "Strawberry", label: "Strawberry", veriety: 101 },
    { value: "Chickoo/ Sapota", label: "Chickoo/ Sapota", veriety: 102 },
    { value: "Pomegranate", label: "Pomegranate", veriety: 103 },
    { value: "Pineapple", label: "Pineapple", veriety: 104 },
    { value: "Plum", label: "Plum", veriety: 105 },
    { value: "Papaya", label: "Papaya", veriety: 106 },
    { value: "Lychee", label: "Lychee", veriety: 107 },
    { value: "Cherry", label: "Cherry", veriety: 108 },
    { value: "Custard Apple", label: "Custard Apple", veriety: 109 },
    { value: "Jackfruit", label: "Jackfruit", veriety: 110 },
    { value: "Cranberry", label: "Cranberry", veriety: 111 },
    { value: "Dragon fruit", label: "Dragon fruit", veriety: 112 },
    { value: "Peach Palm", label: "Peach Palm", veriety: 113 },

    // 18-05-2022
    //categoriesOptions --> Cerals And Pulses
    // { value: "Green peas", label: "Green peas", veriety: 114 },
    { value: "Black Gram", label: "Black Gram", veriety: 115 },
    { value: "Green gram/ Moong", label: "Green gram/ Moong", veriety: 116 },
    { value: "Kabuli Chana/ Chickpea chana", label: "Kabuli Chana/ Chickpea chana", veriety: 117 },
    { value: "Masoor Dal", label: "Masoor Dal", veriety: 118 },
    { value: "Moth Dal", label: "Moth Dal", veriety: 119 },
    { value: "Black-eyed pea/ Karamani", label: "Black-eyed pea/ Karamani", veriety: 120 },
    { value: "Peas (Dry)", label: "Peas (Dry)", veriety: 121 },
    { value: "White peas", label: "White peas", veriety: 122 },
    { value: "Jowar (Sorghum)", label: "Jowar (Sorghum)", veriety: 123 },

    //categoriesOptions -->Spices
    { value: "Coconut", label: "Coconut", veriety: 124 },
    { value: "Ajwain", label: "Ajwain", veriety: 125 },
    { value: "Saunf/ Fennel", label: "Saunf/ Fennel", veriety: 126 },

    //categoriesOptions -->Vegetables
    { value: "Mushroom", label: "Mushroom", veriety: 127 },
    { value: "Coriander leaves", label: "Coriander leaves", veriety: 128 },
    { value: "Elephant yam", label: "Elephant yam", veriety: 129 },
    { value: "Ground Nut", label: "Ground Nut", veriety: 130 },
    { value: "Methi leaves", label: "Methi leaves", veriety: 131 },

    //categoriesOptions -->Oil And Oil Seeds
    { value: "Coconut Oil", label: "Coconut Oil", veriety: 132 },
    { value: "Mustard oil", label: "Mustard oil", veriety: 133 },
    { value: "Ghee", label: "Ghee", veriety: 134 },
    { value: "Gingely oil", label: "Gingely oil", veriety: 135 },

    //categoriesOptions -->Others
    { value: "Cotton", label: "Cotton", veriety: 136 },
    { value: "Jute", label: "Jute", veriety: 137 },
    { value: "Rubber", label: "Rubber", veriety: 138 },
    { value: "Sugar", label: "Sugar", veriety: 139 },
    { value: "Jaggery", label: "Jaggery", veriety: 140 },


    //categoriesOptions -->Metals
    { value: "Aluminium", label: "Aluminium", veriety: 141 },
    { value: "Chromium", label: "Chromium", veriety: 142 },
    { value: "Cobalt", label: "Cobalt", veriety: 143 },
    { value: "Copper", label: "Copper", veriety: 144 },
    { value: "Gold", label: "Gold", veriety: 145 },
    { value: "Iron", label: "Iron", veriety: 146 },
    { value: "Lead", label: "Lead", veriety: 147 },
    { value: "Manganese", label: "Manganese", veriety: 148 },
    { value: "Mercury", label: "Mercury", veriety: 149 },
    { value: "Nickel", label: "Nickel", veriety: 150 },
    { value: "Tin", label: "Tin", veriety: 151 },
    { value: "Silver", label: "Silver", veriety: 152 },
    { value: "Uranium", label: "Uranium", veriety: 153 },
    { value: "Zinc", label: "Zinc", veriety: 154 },

    // 24-05-2022
    //categoriesOptions -->Oil And Oil Seeds
    { value: "Sunflower Oil", label: "Sunflower Oil", veriety: 155 },
    { value: "Olive Oil", label: "Olive Oil", veriety: 156 },
    { value: "Neem Oil", label: "Neem Oil", veriety: 157 },
    { value: "Corn Oil", label: "Corn Oil", veriety: 158 },
    { value: "Peanut Oil", label: "Peanut Oil", veriety: 159 },
    { value: "Sesame Oil", label: "Sesame Oil", veriety: 160 },
    { value: "Avocado Oil", label: "Avocado Oil", veriety: 161 },
    { value: "Walnut Oil", label: "Walnut Oil", veriety: 162 },
    { value: "Grapeseed Oil", label: "Grapeseed Oil", veriety: 163 },
    { value: "Castor Oil", label: "Castor Oil", veriety: 164 },

]

export const verietyOprions = {
    19: [
        { value: "NA", label: "NA" },
        { value: "Bulb Turmeric", label: "Bulb Turmeric", category: 5, commodity: 19 },
        { value: "Finger Tumeric", label: "Finger Tumeric", category: 5, commodity: 19 },
        { value: "Chur Turmeric", label: "Chur Turmeric", category: 5, commodity: 19 },
        { value: "Suvarna", label: "Suvarna", category: 5, commodity: 19 },
        { value: "Suguna", label: "Suguna", category: 5, commodity: 19 },
        { value: "Sudarsana", label: "Sudarsana", category: 5, commodity: 19 },
        { value: "IISR Prabha", label: "IISR Prabha", category: 5, commodity: 19 },
        { value: "IISR Prathibha", label: "IISR Prathibha", category: 5, commodity: 19 },
        { value: "Co-1", label: "Co-1", category: 5, commodity: 19 },
        { value: "BSR-1", label: "BSR-1", category: 5, commodity: 19 },
        { value: "Krishna", label: "Krishna", category: 5, commodity: 19 },
        { value: "Sugandham", label: "Sugandham", category: 5, commodity: 19 },
        { value: "Roma", label: "Roma", category: 5, commodity: 19 },
        { value: "Suroma", label: "Suroma", category: 5, commodity: 19 },
        { value: "Ranga", label: "Ranga", category: 5, commodity: 19 },
        { value: "Rasmi", label: "Rasmi", category: 5, commodity: 19 },
        { value: "Rajendra Sonia", label: "Rajendra Sonia", category: 5, commodity: 19 },
        { value: "IISR Alleppey", label: "IISR Alleppey", category: 5, commodity: 19 },
        { value: "Supreme", label: "Supreme", category: 5, commodity: 19 },
        { value: "IISR Kedaram", label: "IISR Kedaram", category: 5, commodity: 19 },
    ],
    20: [
        { value: "NA", label: "NA" },
        { value: "Common Ginger", label: "Common Ginger", category: 5, commodity: 20 },
        { value: "Galangal", label: "Galangal", category: 5, commodity: 20 },
        { value: "Turmeric", label: "Turmeric", category: 5, commodity: 20 },
        { value: "Peacock Ginger", label: "Peacock Ginger", category: 5, commodity: 20 },
        { value: "White Ginger", label: "White Ginger", category: 5, commodity: 20 },
    ],
    21: [
        { value: "NA", label: "NA" },
        { value: "Softneck Garlic", label: "Softneck Garlic", category: 5, commodity: 21 },
        { value: "Hardneck Garlic", label: "Hardneck Garlic", category: 5, commodity: 21 },
        { value: "ARTICHOKE GARLIC (S)", label: "ARTICHOKE GARLIC (S)", category: 5, commodity: 21 },
        { value: "SILVERSKIN GARLIC (S)", label: "SILVERSKIN GARLIC (S)", category: 5, commodity: 21 },
        { value: "ROCAMBOLE GARLIC (H)", label: "ROCAMBOLE GARLIC (H)", category: 5, commodity: 21 },
        { value: "PORCELAIN GARLIC (H)", label: "PORCELAIN GARLIC (H)", category: 5, commodity: 21 },
        { value: "PURPLE STRIPE GARLIC (H)", label: "PURPLE STRIPE GARLIC (H)", category: 5, commodity: 21 },
        { value: "MARBLED STRIPE GARLIC (H)", label: "MARBLED STRIPE GARLIC (H)", category: 5, commodity: 21 },
        { value: "GLAZED PURPLE GARLIC (H)", label: "GLAZED PURPLE GARLIC (H)", category: 5, commodity: 21 },
        { value: "ASIATIC GARLIC (WB)", label: "ASIATIC GARLIC (WB)", category: 5, commodity: 21 },
        { value: "TURBAN GARLIC (WB)", label: "TURBAN GARLIC (WB)", category: 5, commodity: 21 },
        { value: "CREOLE GARLIC (WB)", label: "CREOLE GARLIC (WB)", category: 5, commodity: 21 },
        { value: "weakly bolting hardnecks", label: "weakly bolting hardnecks", category: 5, commodity: 21 },


    ],
    22: [
        { value: "NA", label: "NA" },
        { value: "Kashmiri Mirch", label: "Kashmiri Mirch", category: 5, commodity: 22 },
        { value: "Guntur Sannam (S4) Chilli", label: "Guntur Sannam (S4) Chilli", category: 5, commodity: 22 },
        { value: "Kaddi Chilli (Byadagi)", label: "Kaddi Chilli (Byadagi)", category: 5, commodity: 22 },
        { value: "Ramnad Mundu/Gundu", label: "Ramnad Mundu/Gundu", category: 5, commodity: 22 },
        { value: "Jwala Chilli", label: "Jwala Chilli", category: 5, commodity: 22 },
        { value: "Dhani Chilli", label: "Dhani Chilli", category: 5, commodity: 22 },
        { value: "Bhut Jolokia", label: "Bhut Jolokia", category: 5, commodity: 22 },
        { value: "Kanthari Chilli", label: "Kanthari Chilli", category: 5, commodity: 22 },
    ],
    23: [
        { value: "NA", label: "NA" },
        { value: "Sadhana (CS-4)", label: "Sadhana (CS-4)", category: 5, commodity: 23 },
        { value: "Sindhu (CS-2)", label: "Sindhu (CS-2)", category: 5, commodity: 23 },
        { value: "Sudha (LCC-128)", label: "Sudha (LCC-128)", category: 5, commodity: 23 },
        { value: "Swathi (CS-6)", label: "Swathi (CS-6)", category: 5, commodity: 23 },
        { value: "APHU Dhania-1 (LCC-170)", label: "APHU Dhania-1 (LCC-170)", category: 5, commodity: 23 },
        { value: "Suguna (LCC-236)", label: "Suguna (LCC-236)", category: 5, commodity: 23 },
        { value: "Suruchi (LCC-234)", label: "Suruchi (LCC-234)", category: 5, commodity: 23 },
        { value: "Susthira (LCC-219)", label: "Susthira (LCC-219)", category: 5, commodity: 23 },
    ],
    24: [
        { value: "NA", label: "NA" },
        { value: "Edible Copra", label: "Edible Copra", category: 5, commodity: 24 },
        { value: "Milling Copra", label: "Milling Copra", category: 5, commodity: 24 },
    ],
    25: [
        { value: "NA", label: "NA" },
        { value: "Black Pepper", label: "Black Pepper", category: 5, commodity: 25 },
        { value: "White Pepper", label: "White Pepper", category: 5, commodity: 25 },
        { value: "Green Pepper", label: "Green Pepper", category: 5, commodity: 25 },
        { value: "Red Pepper", label: "Red Pepper", category: 5, commodity: 25 },
        { value: "Garbled Pepper", label: "Garbled Pepper", category: 5, commodity: 25 },
        { value: "Ungarbled Pepper", label: "Ungarbled Pepper", category: 5, commodity: 25 },
    ],
    26: [
        { value: "NA", label: "NA" },
        { value: "Green cardamom", label: "Green cardamom", category: 5, commodity: 26 },
        { value: "Black cardamom", label: "Black cardamom", category: 5, commodity: 26 },
        { value: "Ground cardamom", label: "Ground cardamom", category: 5, commodity: 26 },
        { value: "White cardamom", label: "White cardamom", category: 5, commodity: 26 },
    ],
    27: [
        { value: "NA", label: "NA" },
        { value: "Forastero", label: "Forastero", category: 5, commodity: 27 },
        { value: "Criollo", label: "Criollo", category: 5, commodity: 27 },
        { value: "Trinitario", label: "Trinitario", category: 5, commodity: 27 },
    ],
    28: [
        { value: "NA", label: "NA" },
        { value: "Vanilla Planifolia", label: "Vanilla Planifolia", category: 5, commodity: 28 },
        { value: "Vanilla Tahitiensis", label: "Vanilla Tahitiensis", category: 5, commodity: 28 },
        { value: "Vanilla Pompona", label: "Vanilla Pompona", category: 5, commodity: 28 },
    ],
    /* 29: [
        { value: "", label: "", category: 5, commodity: 29 },
    ], */
    30: [
        { value: "NA", label: "NA" },
        { value: "Black Cumin Seeds", label: "Black Cumin Seeds", category: 5, commodity: 30 },
        { value: "Bitter Cumin", label: "Bitter Cumin", category: 5, commodity: 30 },
    ],
    31: [
        { value: "NA", label: "NA" },
        { value: "Yellow Mustard", label: "Yellow Mustard", category: 5, commodity: 31 },
        { value: "Brown Mustard", label: "Brown Mustard", category: 5, commodity: 31 },
        { value: "Black Mustard", label: "Black Mustard", category: 5, commodity: 31 },
    ],
    32: [
        { value: "NA", label: "NA" },
        { value: "Golden or Brown Sesame", label: "Golden or Brown Sesame", category: 5, commodity: 32 },
        { value: "White Sesame", label: "White Sesame", category: 5, commodity: 32 },
        { value: "Black Sesame", label: "Black Sesame", category: 5, commodity: 32 },
    ],
    /* 33: [
        { value: "", label: "", category: 5, commodity: 33 },
    ], */
    34: [
        { value: "NA", label: "NA" },
        { value: "Milky White Asafoetida", label: "Milky White Asafoetida", category: 5, commodity: 34 },
        { value: "Red Asafoetida", label: "Red Asafoetida", category: 5, commodity: 34 },
    ],
    35: [
        { value: "NA", label: "NA" },
        { value: "Kashmiri Mirch", label: "Kashmiri Mirch", category: 5, commodity: 35 },
        { value: "Guntur Sannam (S4) Chilli", label: "Guntur Sannam (S4) Chilli", category: 5, commodity: 35 },
        { value: "Kaddi Chilli (Byadagi)", label: "Kaddi Chilli (Byadagi)", category: 5, commodity: 35 },
        { value: "Ramnad Mundu/Gundu", label: "Ramnad Mundu/Gundu", category: 5, commodity: 35 },
        { value: "Jwala Chilli", label: "Jwala Chilli", category: 5, commodity: 35 },
        { value: "Dhani Chilli", label: "Dhani Chilli", category: 5, commodity: 35 },
        { value: "Bhut Jolokia", label: "Bhut Jolokia", category: 5, commodity: 35 },
        { value: "Kanthari Chilli", label: "Kanthari Chilli", category: 5, commodity: 35 },
    ],
    /* 36: [
        { value: "", label: "", category: 5, commodity: 36 },
    ], */
    37: [
        { value: "NA", label: "NA" },
        { value: "Ceylon Cinnamon", label: "Ceylon Cinnamon", category: 5, commodity: 37 },
        { value: "Korintje Cinnamon", label: "Korintje Cinnamon", category: 5, commodity: 37 },
        { value: "Saigon Cinnamon", label: "Saigon Cinnamon", category: 5, commodity: 37 },
        { value: "Royal Cinnamon", label: "Royal Cinnamon", category: 5, commodity: 37 },
    ],
    38: [
        { value: "NA", label: "NA" },
        { value: "Penang", label: "Penang", category: 5, commodity: 38 },
        { value: "Zanzibar", label: "Zanzibar", category: 5, commodity: 38 },
        { value: "Amboyan", label: "Amboyan", category: 5, commodity: 38 },
    ],
    39: [
        { value: "NA", label: "NA" },
        { value: "Bhagwa", label: "Bhagwa", category: 5, commodity: 39 },
        { value: "Arakta", label: "Arakta", category: 5, commodity: 39 },
        { value: "Mridula", label: "Mridula", category: 5, commodity: 39 },
        { value: "Dholka", label: "Dholka", category: 5, commodity: 39 },
        { value: "Ganesh", label: "Ganesh", category: 5, commodity: 39 },
        { value: "Ruby", label: "Ruby", category: 5, commodity: 39 },
        { value: "Alandi or Vadki", label: "Alandi or Vadki", category: 5, commodity: 39 },
        { value: "Co 1", label: "Co 1", category: 5, commodity: 39 },
        { value: "IIHR selection", label: "IIHR selection", category: 5, commodity: 39 },
        { value: "Jyoti", label: "Jyoti", category: 5, commodity: 39 },
        { value: "Kabul", label: "Kabul", category: 5, commodity: 39 },
        { value: "Kandhari", label: "Kandhari", category: 5, commodity: 39 },
        { value: "Muskat", label: "Muskat", category: 5, commodity: 39 },
        { value: "Paper Shelled", label: "Paper Shelled", category: 5, commodity: 39 },
        { value: "P23", label: "P23", category: 5, commodity: 39 },
        { value: "P26", label: "P26", category: 5, commodity: 39 },
        { value: "Spanish Ruby", label: "Spanish Ruby", category: 5, commodity: 39 },
        { value: "Yercaud 1", label: "Yercaud 1", category: 5, commodity: 39 },
    ],
    40: [
        { value: "NA", label: "NA" },
        { value: "California Bay Leaves", label: "California Bay Leaves", category: 5, commodity: 40 },
        { value: "Turkish Bay Leaves (Mediterranean)", label: "Turkish Bay Leaves (Mediterranean)", category: 5, commodity: 40 },
        { value: "Indonesian Bay Leaf", label: "Indonesian Bay Leaf", category: 5, commodity: 40 },
        { value: "Indian Bay Leaf", label: "Indian Bay Leaf", category: 5, commodity: 40 },
    ],
    /* 41: [
        { value: "", label: "", category: 5, commodity: 41 },
    ], */
    42: [
        { value: "NA", label: "NA" },
        { value: "Green Soybeans", label: "Green Soybeans", category: 5, commodity: 42 },
        { value: "Mature Soybeans", label: "Mature Soybeans", category: 5, commodity: 42 },
        { value: "Dried Soybeans", label: "Dried Soybeans", category: 5, commodity: 42 },
        { value: "Yellow Soybean", label: "Yellow Soybean", category: 5, commodity: 42 },
        { value: "Black Soybean", label: "Black Soybean", category: 5, commodity: 42 },
        { value: "Red Soybean", label: "Red Soybean", category: 5, commodity: 42 },
        { value: "Brown Soybean", label: "Brown Soybean", category: 5, commodity: 42 },
        { value: "White Soybean", label: "White Soybean", category: 5, commodity: 42 },
        { value: "Kurakake Bean", label: "Kurakake Bean", category: 5, commodity: 42 },
    ],
    43: [
        { value: "NA", label: "NA" },
        { value: "Bermuda onions", label: "Bermuda onions", category: 5, commodity: 43 },
        { value: "Boiling onions", label: "Boiling onions", category: 5, commodity: 43 },
        { value: "Chives", label: "Chives", category: 5, commodity: 43 },
        { value: "Cipollini onions", label: "Cipollini onions", category: 5, commodity: 43 },
        { value: "Cocktail onions", label: "Cocktail onions", category: 5, commodity: 43 },
        { value: "Egyptian onions", label: "Egyptian onions", category: 5, commodity: 43 },
        { value: "Green onions", label: "Green onions", category: 5, commodity: 43 },
        { value: "Leeks", label: "Leeks", category: 5, commodity: 43 },
        { value: "Maui onions", label: "Maui onions", category: 5, commodity: 43 },
        { value: "Pearl onions", label: "Pearl onions", category: 5, commodity: 43 },
        { value: "Pickling onions", label: "Pickling onions", category: 5, commodity: 43 },
        { value: "Red onions", label: "Red onions", category: 5, commodity: 43 },
        { value: "Red wing onions", label: "Red wing onions", category: 5, commodity: 43 },
        { value: "Shallots", label: "Shallots", category: 5, commodity: 43 },
        { value: "Spanish onions", label: "Spanish onions", category: 5, commodity: 43 },
        { value: "Texas supersweet onions", label: "Texas supersweet onions", category: 5, commodity: 43 },
        { value: "Vidalia onions", label: "Vidalia onions", category: 5, commodity: 43 },
        { value: "Walla Walla Sweet onions", label: "Walla Walla Sweet onions", category: 5, commodity: 43 },
        { value: "Welsh onions", label: "Welsh onions", category: 5, commodity: 43 },
        { value: "White onions", label: "White onions", category: 5, commodity: 43 },
        { value: "Yellow onions", label: "Yellow onions", category: 5, commodity: 43 },
    ],
    124: [
        { value: "NA", label: "NA" }
    ],
    125: [
        { value: "NA", label: "NA" },
    ],
    126: [
        { value: "NA", label: "NA" },
    ],

}

export const checkVerity = [
    { value: "Turmeric", label: "Turmeric", veriety: 19 },
    { value: "Coriander", label: "Coriander", veriety: 23 },
    // { value: "Jeera", label: "Jeera", veriety: 21 },
    { value: "Ginger", label: "Ginger", veriety: 20 },
    { value: "Garlic", label: "Garlic", veriety: 21 },
    { value: "Green Chilli", label: "Green Chilli", veriety: 22 },
    { value: "Copra", label: "Copra", veriety: 24 },
    { value: "Pepper", label: "Pepper", veriety: 25 },
    { value: "Cardamom (S)", label: "Cardamom (S)", veriety: 26 },
    { value: "Cocoa", label: "Cocoa", veriety: 27 },
    { value: "Vanilla", label: "Vanilla", veriety: 28 },
    { value: "Star Aniseed", label: "Star Aniseed", veriety: 29 },
    { value: "Cumin Seeds", label: "Cumin Seeds", veriety: 30 },
    { value: "Mustard", label: "Mustard", veriety: 31 },
    { value: "Sesame", label: "Sesame", veriety: 32 },
    { value: "Fenugreek", label: "Fenugreek", veriety: 33 },
    { value: "Asafoetida", label: "Asafoetida", veriety: 34 },
    { value: "Red Dry Chilli", label: "Red Dry Chilli", veriety: 35 },
    { value: "Aniseed", label: "Aniseed", veriety: 36 },
    { value: "Cinnamon", label: "Cinnamon", veriety: 37 },
    { value: "Cloves", label: "Cloves", veriety: 38 },
    { value: "Pomegranate Seeds", label: "Pomegranate Seeds", veriety: 39 },
    { value: "Bay Leaf", label: "Bay Leaf", veriety: 40 },
    { value: "Lemon Grass", label: "Lemon Grass", veriety: 41 },
    { value: "Soya", label: "Soya", veriety: 42 },
    { value: "Onion", label: "Onion", veriety: 43 },
]